# language: zh-TW
# Generated by sa-expert
# Source: pm/features/appointment_management.feature
# Project scan date: 2026-04-16

Feature: 預約管理
  對應模組：後端 Controller / Service / Repository 三層式架構
  資料實體：Appointment -> JSON 檔案 data/appointments.json
  API 基礎路徑：/api/appointments

  Background:
    Given 系統已啟動且資料目錄已建立
    And owners.json 中已有飼主 "owner_001"（王小明）
    And pets.json 中已有寵物 "pet_001"（Lucky）關聯 "owner_001"

  # ===================================================================
  # 新增預約
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 成功新增預約
    When 呼叫 POST "/api/appointments" 並帶入以下 JSON：
      """
      {
        "ownerId": "owner_001",
        "petId": "pet_001",
        "date": "2026-04-20",
        "time": "14:00",
        "note": ""
      }
      """
    Then 回應狀態碼應為 201
    And 回應 JSON 應包含自動產生的 "id" 欄位（格式如 "appt_xxx"）
    And 回應 JSON 的 "status" 應為 "已預約"
    And 回應 JSON 的 "createdAt" 應為 ISO 8601 格式
    And appointments.json 中應存在該筆預約

  @backend @unit-test
  Scenario Outline: 後端 - 新增預約缺少必填欄位 - 回傳 400
    When 呼叫 POST "/api/appointments" 並帶入缺少 "<欄位名稱>" 的 JSON
    Then 回應狀態碼應為 400
    And 回應 JSON 的 error.message 應包含 "<欄位名稱>" 為必填
    Examples:
      | 欄位名稱 |
      | ownerId  |
      | petId    |
      | date     |
      | time     |

  @backend @unit-test
  Scenario: 後端 - 同一寵物可有多筆不同日期的預約
    Given appointments.json 中已有 "pet_001" 在 "2026-04-20" 的預約
    When 呼叫 POST "/api/appointments" 帶入 petId "pet_001"、date "2026-04-27"、time "14:00"
    Then 回應狀態碼應為 201
    And appointments.json 中 "pet_001" 應有兩筆預約

  @backend @unit-test
  Scenario: 後端 - 同一飼主的多隻寵物可在同日建立多筆預約
    Given pets.json 中另有寵物 "pet_002"（Mimi）關聯 "owner_001"
    When 呼叫 POST "/api/appointments" 帶入 petId "pet_001"、date "2026-04-20"、time "10:00"
    And 呼叫 POST "/api/appointments" 帶入 petId "pet_002"、date "2026-04-20"、time "14:00"
    Then appointments.json 中 "2026-04-20" 應有兩筆預約

  @backend @unit-test
  Scenario: 後端 - 新增預約時填寫備註
    When 呼叫 POST "/api/appointments" 帶入 note 為 "客戶要求使用低敏洗毛精"
    Then 回應狀態碼應為 201
    And 回應 JSON 的 "note" 應為 "客戶要求使用低敏洗毛精"

  # ===================================================================
  # 編輯預約
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 成功編輯預約日期與時間
    Given appointments.json 中已有預約 "appt_001"，date "2026-04-20"、time "14:00"
    When 呼叫 PUT "/api/appointments/appt_001" 帶入 date "2026-04-21"、time "10:00"
    Then 回應狀態碼應為 200
    And 回應 JSON 的 "date" 應為 "2026-04-21"
    And 回應 JSON 的 "time" 應為 "10:00"
    And 回應 JSON 的 "updatedAt" 應晚於原始值

  @backend @unit-test
  Scenario: 後端 - 已產生契約後仍可修改預約資料
    Given appointments.json 中已有預約 "appt_001"
    And grooming-records.json 中已有關聯 "appt_001" 的美容紀錄且已產生契約
    When 呼叫 PUT "/api/appointments/appt_001" 修改 note
    Then 回應狀態碼應為 200

  # ===================================================================
  # 取消預約
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 成功取消預約並填寫取消原因
    Given appointments.json 中已有預約 "appt_001"，status 為 "已預約"
    When 呼叫 PUT "/api/appointments/appt_001" 帶入以下 JSON：
      """
      {
        "status": "已取消",
        "cancelReason": "飼主臨時有事"
      }
      """
    Then 回應狀態碼應為 200
    And 回應 JSON 的 "status" 應為 "已取消"
    And 回應 JSON 的 "cancelReason" 應為 "飼主臨時有事"
    And appointments.json 中 "appt_001" 的資料不應被刪除

  @backend @unit-test
  Scenario: 後端 - 取消預約時未填寫取消原因 - 回傳 400
    Given appointments.json 中已有預約 "appt_001"，status 為 "已預約"
    When 呼叫 PUT "/api/appointments/appt_001" 帶入 status "已取消" 但無 cancelReason
    Then 回應狀態碼應為 400
    And 回應 JSON 的 error.message 應包含 "取消原因" 為必填

  @frontend @unit-test
  Scenario: 前端 - 新增預約表單必填檢查
    Given 使用者在預約新增頁面
    When 使用者未選擇飼主、寵物、日期或時間
    Then 表單應顯示對應的必填驗證錯誤
    And 不應呼叫 POST "/api/appointments" API

  @frontend @unit-test
  Scenario: 前端 - 取消預約時必須填寫取消原因
    Given 使用者在預約詳細頁面，預約狀態為「已預約」
    When 使用者選擇取消預約但未填寫取消原因
    Then 應顯示取消原因為必填的驗證錯誤
    And 不應呼叫 PUT "/api/appointments/:appointmentId" API
