# language: zh-TW
# Generated by sa-expert
# Source: pm/features/calendar_view.feature
# Project scan date: 2026-04-16

Feature: 行事曆檢視
  對應模組：前端 Vue 元件（CalendarView）+ 後端預約 API
  資料來源：GET /api/appointments（依日期區間查詢）

  Background:
    Given 系統已啟動且資料目錄已建立
    And appointments.json 中已有以下預約：
      | id       | ownerId   | petId   | date       | time  | status |
      | appt_001 | owner_002 | pet_002 | 2026-04-20 | 10:00 | 已預約 |
      | appt_002 | owner_001 | pet_001 | 2026-04-20 | 14:00 | 已預約 |
      | appt_003 | owner_003 | pet_003 | 2026-04-25 | 15:00 | 已預約 |

  # ===================================================================
  # 後端 - 依日期區間取得預約
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 依月份區間取得預約列表
    When 呼叫 GET "/api/appointments?startDate=2026-04-01&endDate=2026-04-30"
    Then 回應狀態碼應為 200
    And 回應 JSON 陣列應包含 3 筆預約

  @backend @unit-test
  Scenario: 後端 - 依指定日期取得預約列表
    When 呼叫 GET "/api/appointments/date/2026-04-20"
    Then 回應狀態碼應為 200
    And 回應 JSON 陣列應包含 2 筆預約
    And 回應應依 time 升序排列

  @backend @unit-test
  Scenario: 後端 - 查詢無預約的日期
    When 呼叫 GET "/api/appointments/date/2026-04-01"
    Then 回應狀態碼應為 200
    And 回應 JSON 陣列應為空

  # ===================================================================
  # 前端 - 月檢視
  # ===================================================================

  @frontend @unit-test
  Scenario: 前端 - 月檢視載入時呼叫 API 取得當月預約
    Given 使用者在行事曆頁面，當前為 2026 年 4 月月檢視
    When 頁面載入時
    Then 前端應呼叫 GET "/api/appointments?startDate=2026-04-01&endDate=2026-04-30"
    And 2026-04-20 的日期格應顯示預約數 2 或寵物名稱
    And 2026-04-25 的日期格應顯示預約數 1 或寵物名稱
    And 無預約的日期格不應顯示預約摘要

  # ===================================================================
  # 前端 - 週檢視
  # ===================================================================

  @frontend @unit-test
  Scenario: 前端 - 週檢視顯示該週預約
    Given 使用者在行事曆頁面，切換至週檢視，顯示包含 2026-04-20 的那週
    Then 前端應呼叫 GET "/api/appointments" 帶入該週的 startDate 與 endDate
    And 2026-04-20 應顯示預約摘要
    And 該週其他無預約日期不應顯示預約摘要

  # ===================================================================
  # 前端 - 日檢視
  # ===================================================================

  @frontend @unit-test
  Scenario: 前端 - 日檢視顯示該日所有預約
    Given 使用者在行事曆頁面，切換至日檢視，日期為 2026-04-20
    Then 前端應呼叫 GET "/api/appointments/date/2026-04-20"
    And 應顯示 10:00 Mimi 和 14:00 Lucky 的預約摘要

  # ===================================================================
  # 前端 - 檢視模式切換
  # ===================================================================

  @frontend @unit-test
  Scenario: 前端 - 切換月/週/日檢視模式
    Given 使用者在行事曆頁面
    When 使用者點擊「月」檢視按鈕
    Then 行事曆應顯示為月曆格式
    When 使用者點擊「週」檢視按鈕
    Then 行事曆應顯示為週曆格式
    When 使用者點擊「日」檢視按鈕
    Then 行事曆應顯示為日曆格式

  # ===================================================================
  # 前端 - 日期切換
  # ===================================================================

  @frontend @unit-test
  Scenario: 前端 - 月檢視切換月份
    Given 使用者在月檢視，當前為 2026 年 4 月
    When 使用者點擊下個月按鈕
    Then 行事曆應顯示 2026 年 5 月
    And 前端應重新呼叫 API 取得 5 月預約資料
    When 使用者點擊上個月按鈕
    Then 行事曆應顯示 2026 年 4 月

  @frontend @unit-test
  Scenario: 前端 - 週檢視切換週
    Given 使用者在週檢視
    When 使用者點擊下週按鈕
    Then 行事曆應顯示下週的日期範圍
    And 前端應重新呼叫 API 取得該週預約資料

  @frontend @unit-test
  Scenario: 前端 - 日檢視切換日期
    Given 使用者在日檢視，當前為 2026-04-20
    When 使用者點擊隔天按鈕
    Then 行事曆應顯示 2026-04-21
    And 前端應呼叫 GET "/api/appointments/date/2026-04-21"

  # ===================================================================
  # 前端 - 點擊開啟當日預約列表
  # ===================================================================

  @frontend @unit-test
  Scenario: 前端 - 點擊日期導向當日預約列表頁
    Given 使用者在月檢視
    When 使用者點擊 2026-04-20 的日期格
    Then 頁面應導向 "/appointments/daily/2026-04-20" 當日預約列表頁

  @frontend @unit-test
  Scenario: 前端 - 已取消預約在行事曆中有明確標示
    Given appointments.json 中 "appt_002" 的 status 為 "已取消"
    When 使用者在行事曆中檢視 2026-04-20
    Then "Lucky" 的預約應以取消樣式（如刪除線或灰色）顯示
