# language: zh-TW
# Generated by sa-expert
# Source: pm/features/contract_pdf_generation.feature
# Project scan date: 2026-04-16

Feature: 契約 PDF 產生
  對應模組：後端 ContractController / ContractService / PdfGenerator
  API 基礎路徑：/api/contracts
  PDF 模板：唯讀，不得修改
  PDF 輸出：generated-contracts/ 目錄

  Background:
    Given 系統已啟動且資料目錄已建立
    And PDF 模板檔案存在於 settings.json 設定的路徑
    And owners.json 中已有飼主 "owner_001"（王小明），資料如下：
      """
      {
        "id": "owner_001",
        "name": "王小明",
        "nationalId": "A123456789",
        "phone": "0912345678",
        "address": "桃園市桃園區中正路1號",
        "emergencyContactName": "王太太",
        "emergencyContactPhone": "0987654321",
        "emergencyContactRelationship": "配偶",
        "isStoredValueCustomer": true,
        "storedValueBalance": 5000
      }
      """
    And pets.json 中已有寵物 "pet_001"（Lucky），資料如下：
      """
      {
        "id": "pet_001",
        "ownerId": "owner_001",
        "name": "Lucky",
        "species": "犬",
        "breed": "貴賓",
        "gender": "公",
        "age": "3歲",
        "isNeutered": true,
        "chipNumber": "900000000012345",
        "personality": ["親人", "不會咬人", "不會咬狗貓"],
        "physicalExamination": { "eyes": "正常", "ears": "正常", "teeth": "正常", "limbs": "正常", "skin": "正常", "fur": "正常" },
        "medicalHistory": []
      }
      """
    And grooming-records.json 中已有紀錄 "rec_001"，appointmentId: "appt_001", services: [{"item": "洗澡", "price": 500}]

  # ===================================================================
  # 後端 - 成功產生契約
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 成功產生契約 PDF
    When 呼叫 POST "/api/contracts/generate" 並帶入以下 JSON：
      """
      { "recordId": "rec_001" }
      """
    Then 回應狀態碼應為 201
    And 回應 JSON 應包含：
      | 欄位            | 說明                                     |
      | contractPath    | PDF 檔案路徑                             |
      | version         | 版本編號                                 |
      | generatedAt     | 產生時間（ISO 8601）                     |
      | generatedBy     | 產生者名稱                               |
    And generated-contracts/ 目錄下應存在新的 PDF 檔案
    And grooming-records.json 中 "rec_001" 的 contractPaths 應包含該 PDF 路徑
    And grooming-records.json 中 "rec_001" 應記錄 contractGeneratedAt 和 contractGeneratedBy

  # ===================================================================
  # 後端 - 第 1 頁套版（PdfGenerator 模組）
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - PdfGenerator 第 1 頁犬貓資訊套版
    When PdfGenerator 處理第 1 頁套版
    Then 第 1 頁應在犬貓名稱位置寫入 "Lucky"
    And 第 1 頁應在種類「犬」位置畫勾選標記
    And 第 1 頁應在品種位置寫入 "貴賓"
    And 第 1 頁應在性別「公」位置畫勾選標記
    And 第 1 頁應在年齡位置寫入 "3歲"
    And 第 1 頁應在晶片號碼位置寫入 "900000000012345"

  @backend @unit-test
  Scenario: 後端 - PdfGenerator 第 1 頁無晶片時帶入未登記身分識別方式
    Given 寵物 "pet_001" chipNumber 為空，unregisteredIdMethod 為 "左耳有黑色記號"
    When PdfGenerator 處理第 1 頁套版
    Then 第 1 頁應在未登記身分識別方式位置勾選並寫入 "左耳有黑色記號"

  @backend @unit-test
  Scenario: 後端 - PdfGenerator 第 1 頁飼主（甲方）資訊套版
    When PdfGenerator 處理第 1 頁套版
    Then 第 1 頁應在飼主姓名位置寫入 "王小明"
    And 第 1 頁應在身分證字號位置寫入 "A123456789"
    And 第 1 頁應在聯絡電話位置寫入 "0912345678"
    And 第 1 頁應在通訊地址位置寫入 "桃園市桃園區中正路1號"
    And 第 1 頁應在緊急聯絡人位置寫入 "王太太"
    And 第 1 頁應在緊急聯絡人電話位置寫入 "0987654321"

  @backend @unit-test
  Scenario: 後端 - PdfGenerator 第 1 頁帶入飼主指定獸醫院
    Given 飼主 "owner_001" preferredAnimalHospital 為 "仁愛動物醫院"
    When PdfGenerator 處理第 1 頁套版
    Then 第 1 頁應在指定動物醫療機構位置寫入 "仁愛動物醫院"

  @backend @unit-test
  Scenario: 後端 - PdfGenerator 第 1 頁飼主未填獸醫院時帶入店家預設
    Given 飼主 "owner_001" preferredAnimalHospital 為空
    When PdfGenerator 處理第 1 頁套版
    Then 第 1 頁應在指定動物醫療機構位置寫入 "安欣動物醫院"

  # ===================================================================
  # 後端 - 第 3 頁套版
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - PdfGenerator 第 3 頁簽署日期使用民國年格式
    Given 系統日期為 2026-04-20
    When PdfGenerator 處理第 3 頁套版
    Then 第 3 頁簽署日期位置應寫入 "中華民國 115 年 04 月 20 日"

  @backend @unit-test
  Scenario: 後端 - 民國年轉換邏輯正確
    Given 西元年為 2026
    When 呼叫民國年轉換函式
    Then 民國年應為 115（2026 - 1911 = 115）

  # ===================================================================
  # 後端 - 第 4 頁套版
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - PdfGenerator 第 4 頁飼主資訊套版
    When PdfGenerator 處理第 4 頁套版
    Then 第 4 頁應在飼主姓名位置寫入 "王小明"
    And 第 4 頁應在身分證字號位置寫入 "A123456789"
    And 第 4 頁應在聯絡電話位置寫入 "0912345678"
    And 第 4 頁應在聯絡地址位置寫入 "桃園市桃園區中正路1號"
    And 第 4 頁應在緊急聯絡人位置寫入 "王太太"
    And 第 4 頁應在緊急聯絡人與飼主關係位置寫入 "配偶"
    And 第 4 頁應在緊急聯絡人電話位置寫入 "0987654321"

  @backend @unit-test
  Scenario: 後端 - PdfGenerator 第 4 頁寵物資訊套版
    When PdfGenerator 處理第 4 頁套版
    Then 第 4 頁應在寵物名稱位置寫入 "Lucky"
    And 第 4 頁應在性別「公」位置畫勾選標記
    And 第 4 頁應在種類「犬」位置畫勾選標記
    And 第 4 頁應在品種位置寫入 "貴賓"
    And 第 4 頁應在年齡位置寫入 "3歲"
    And 第 4 頁應在結育「已結育」位置畫勾選標記
    And 第 4 頁應在晶片號碼位置寫入 "900000000012345"

  @backend @unit-test
  Scenario: 後端 - PdfGenerator 第 4 頁服務項目與費用套版
    Given 美容紀錄 services 為 [{"item": "洗澡", "price": 500}]
    When PdfGenerator 處理第 4 頁套版
    Then 第 4 頁應在「洗澡」位置畫勾選標記
    And 第 4 頁應在洗澡費用位置寫入 "500"

  @backend @unit-test
  Scenario: 後端 - PdfGenerator 第 4 頁多項服務套版
    Given 美容紀錄 services 為 [{"item": "洗澡", "price": 500}, {"item": "美容", "price": 800}]
    When PdfGenerator 處理第 4 頁套版
    Then 第 4 頁應在「洗澡」位置勾選並寫入費用 500
    And 第 4 頁應在「美容」位置勾選並寫入費用 800

  @backend @unit-test
  Scenario: 後端 - PdfGenerator 第 4 頁儲值型客戶帶入剩餘儲值金
    Given 飼主 storedValueBalance 為 5000，本次費用合計 500
    When PdfGenerator 處理第 4 頁套版
    Then 第 4 頁應在儲值金額位置寫入 "4500"

  @backend @unit-test
  Scenario: 後端 - PdfGenerator 第 4 頁非儲值型客戶不帶入儲值金額
    Given 飼主 isStoredValueCustomer 為 false
    When PdfGenerator 處理第 4 頁套版
    Then 第 4 頁儲值金額位置不應寫入任何值

  @backend @unit-test
  Scenario: 後端 - PdfGenerator 第 4 頁寵物個性勾選套版
    Given 寵物 personality 為 ["親人", "不會咬人", "不會咬狗貓"]
    When PdfGenerator 處理第 4 頁套版
    Then 第 4 頁應在「親人」位置畫勾選標記
    And 第 4 頁應在「不會咬人」位置畫勾選標記
    And 第 4 頁應在「不會咬狗貓」位置畫勾選標記
    And 第 4 頁不應在「容易緊張」位置畫勾選標記

  @backend @unit-test
  Scenario: 後端 - PdfGenerator 第 4 頁獸醫院資訊套版
    Given 飼主指定獸醫院：名稱 "仁愛動物醫院"、電話 "03-1234567"、地址 "桃園市中壢區中正路100號"
    When PdfGenerator 處理第 4 頁套版
    Then 第 4 頁飼主指定獸醫院名稱應寫入 "仁愛動物醫院"
    And 第 4 頁飼主指定獸醫院電話應寫入 "03-1234567"
    And 第 4 頁飼主指定獸醫院地址應寫入 "桃園市中壢區中正路100號"
    And 第 4 頁店家獸醫院名稱應寫入 "安欣動物醫院"
    And 第 4 頁店家獸醫院電話應寫入 "03-3367775"
    And 第 4 頁店家獸醫院地址應寫入 "桃園市桃園區中福街60號"

  @backend @unit-test
  Scenario: 後端 - PdfGenerator 第 4 頁身體狀態檢視套版
    Given 美容紀錄 physicalExamination 為：eyes "正常"、ears "異常"、teeth "正常"、limbs "正常"、skin "異常"、fur "打結"
    When PdfGenerator 處理第 4 頁套版
    Then 第 4 頁眼睛應勾選「正常」
    And 第 4 頁耳朵應勾選「異常」
    And 第 4 頁皮膚應勾選「異常」
    And 第 4 頁皮毛應勾選「打結」

  @backend @unit-test
  Scenario: 後端 - PdfGenerator 第 4 頁寵物病史套版
    Given 美容紀錄 medicalHistory 為 ["心臟病", "氣喘", "癲癇"]
    When PdfGenerator 處理第 4 頁套版
    Then 第 4 頁應在「心臟病」位置畫勾選標記
    And 第 4 頁應在「氣喘」位置畫勾選標記
    And 第 4 頁應在「癲癇」位置畫勾選標記
    And 第 4 頁不應在「骨折」位置畫勾選標記

  @backend @unit-test
  Scenario: 後端 - PdfGenerator 第 4 頁病史「其它」帶入內容
    Given 美容紀錄 medicalHistory 包含 "其它"，medicalHistoryOther 為 "長期皮膚過敏"
    When PdfGenerator 處理第 4 頁套版
    Then 第 4 頁應在「其它」位置畫勾選標記
    And 第 4 頁應在其它內容位置寫入 "長期皮膚過敏"

  @backend @unit-test
  Scenario: 後端 - PdfGenerator 第 4 頁其他備註套版
    Given 美容紀錄 otherNotes 為 "客戶要求保留尾巴毛長"
    When PdfGenerator 處理第 4 頁套版
    Then 第 4 頁第 8 項應寫入 "客戶要求保留尾巴毛長"

  @backend @unit-test
  Scenario: 後端 - PdfGenerator 第 4 頁簽署日期使用民國年格式
    Given 系統日期為 2026-04-20
    When PdfGenerator 處理第 4 頁套版
    Then 第 4 頁簽署日期應寫入 "中華民國 115 年 04 月 20 日"

  # ===================================================================
  # 後端 - 第 1 頁與第 4 頁重複欄位
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 第 1 頁與第 4 頁重複欄位都正確套版
    When PdfGenerator 產生完整 PDF
    Then 第 1 頁與第 4 頁的飼主姓名都應寫入 "王小明"
    And 第 1 頁與第 4 頁的聯絡電話都應寫入 "0912345678"
    And 第 1 頁與第 4 頁的寵物名稱都應寫入 "Lucky"

  # ===================================================================
  # 後端 - 版本管理
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 同一預約重複產生契約時產生新版本
    Given grooming-records.json 中 "rec_001" 已有 contractPaths 包含 v1 路徑
    When 呼叫 POST "/api/contracts/generate" 帶入 recordId "rec_001"
    Then 回應狀態碼應為 201
    And 回應 JSON 的 "version" 應為 2
    And v1 的 PDF 檔案不應被覆蓋
    And grooming-records.json 中 "rec_001" 的 contractPaths 應包含 v1 和 v2

  @backend @unit-test
  Scenario: 後端 - 取得契約版本列表
    Given grooming-records.json 中 "rec_001" 已有 v1 和 v2 兩份契約
    When 呼叫 GET "/api/contracts/rec_001/versions"
    Then 回應狀態碼應為 200
    And 回應 JSON 陣列應包含 2 筆版本，每筆包含 version、path、generatedAt

  @backend @unit-test
  Scenario: 後端 - 下載契約 PDF
    Given grooming-records.json 中 "rec_001" 已有契約 PDF
    When 呼叫 GET "/api/contracts/rec_001"
    Then 回應狀態碼應為 200
    And 回應 Content-Type 應為 "application/pdf"

  # ===================================================================
  # 後端 - 檔名規則
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - PDF 檔名使用跨平台安全格式
    When 產生契約 PDF
    Then PDF 檔名應符合格式 "YYYYMMDD_HHmm_Lucky_王小明_契約.pdf"
    And 檔名不應包含 Windows 不允許的字元

  @backend @unit-test
  Scenario: 後端 - 重複產生契約時檔名加上版本編號
    Given 已存在 v1 的契約 PDF
    When 再次產生契約 PDF
    Then 新 PDF 檔名應包含 "_v2" 後綴

  # ===================================================================
  # 後端 - PDF 模板保護
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 產生契約後原始 PDF 模板不被修改
    Given PDF 模板檔案的修改時間與大小已記錄
    When 呼叫 POST "/api/contracts/generate"
    Then PDF 模板檔案的修改時間與大小應與產生前一致

  # ===================================================================
  # 後端 - 異常處理
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - PDF 模板不存在時回傳 500
    Given PDF 模板檔案不存在
    When 呼叫 POST "/api/contracts/generate" 帶入 recordId "rec_001"
    Then 回應狀態碼應為 500
    And 回應 JSON 的 error.message 應包含 "PDF 模板不存在"
    And grooming-records.json 中 "rec_001" 不應被修改

  @backend @unit-test
  Scenario: 後端 - 必填欄位未完整時回傳 400
    Given 飼主 "owner_001" nationalId 為空
    When 呼叫 POST "/api/contracts/generate" 帶入 recordId "rec_001"
    Then 回應狀態碼應為 400
    And 回應 JSON 的 error.message 應包含 "必填欄位不完整"

  @backend @unit-test
  Scenario: 後端 - PDF 產生失敗時保留美容紀錄
    Given PDF 產生過程模擬拋出例外
    When 呼叫 POST "/api/contracts/generate"
    Then 回應狀態碼應為 500
    And grooming-records.json 中 "rec_001" 應保持不變

  @backend @unit-test
  Scenario: 後端 - 輸出目錄無寫入權限時回傳 500
    Given generated-contracts/ 目錄沒有寫入權限
    When 呼叫 POST "/api/contracts/generate"
    Then 回應狀態碼應為 500
    And 回應 JSON 的 error.message 應包含 "無法寫入輸出目錄"

  # ===================================================================
  # 前端 - 契約產生操作
  # ===================================================================

  @frontend @unit-test
  Scenario: 前端 - 按下產生契約後呼叫 API
    Given 使用者在美容服務資料頁，美容紀錄已保存
    When 使用者按下產生契約按鈕
    Then 前端應呼叫 POST "/api/contracts/generate" 帶入 recordId
    And API 回應 201 後應顯示產生成功訊息
    And 應提供下載 PDF 的連結

  @frontend @unit-test
  Scenario: 前端 - 顯示契約版本列表
    Given 使用者在美容服務資料頁
    When 前端呼叫 GET "/api/contracts/rec_001/versions" 取得版本列表
    Then 應顯示每個版本的版本號與產生時間
    And 每個版本應提供下載連結

  @frontend @unit-test
  Scenario: 前端 - API 回傳錯誤時顯示錯誤訊息
    Given 使用者按下產生契約按鈕
    When API 回傳 500 且 error.message 為 "PDF 模板不存在"
    Then 頁面應顯示「PDF 模板不存在」的錯誤訊息
