# language: zh-TW
# Generated by sa-expert
# Source: pm/features/customer_form.feature
# Project scan date: 2026-04-16

Feature: 客戶資料填寫頁
  對應模組：前端 CustomerForm 頁面元件 + 後端 OwnerController / PetController
  API：POST /api/owners, POST /api/pets
  限制：不需登入、不顯示其他客戶資料、不提供店內管理功能

  Background:
    Given 系統已啟動且資料目錄已建立

  # ===================================================================
  # 前端 - 開啟客戶填寫頁
  # ===================================================================

  @frontend @unit-test
  Scenario: 前端 - 美容師開啟客戶資料填寫頁
    Given 使用者（美容師）在系統管理畫面
    When 使用者點擊「開啟客戶資料填寫」按鈕
    Then 頁面應導向客戶資料填寫頁面路由（如 "/customer-form"）
    And 頁面不應顯示登入表單或帳號輸入欄位

  # ===================================================================
  # 前端 - 飼主資料填寫
  # ===================================================================

  @frontend @unit-test
  Scenario: 前端 - 客戶填寫飼主基本資料表單
    Given 使用者在客戶資料填寫頁
    Then 表單應提供以下飼主欄位：
      | 欄位名稱               | HTML 類型  | 必填 |
      | 姓名                   | text       | 是   |
      | 身分證字號             | text       | 是   |
      | 聯絡電話               | tel        | 是   |
      | 通訊地址               | text       | 是   |
      | 緊急聯絡人             | text       | 是   |
      | 緊急聯絡人電話         | tel        | 是   |
      | 緊急聯絡人與飼主關係   | text       | 是   |
      | 指定動物醫療機構       | text       | 否   |
      | 指定動物醫療機構電話   | tel        | 否   |
      | 指定動物醫療機構地址   | text       | 否   |

  # ===================================================================
  # 前端 - 寵物資料填寫
  # ===================================================================

  @frontend @unit-test
  Scenario: 前端 - 客戶填寫寵物基本資料
    Given 使用者在客戶資料填寫頁
    Then 寵物表單應提供以下欄位：
      | 欄位名稱             | HTML 類型     | 必填 |
      | 名稱                 | text          | 是   |
      | 種類                 | select/radio  | 是   |
      | 品種                 | text          | 是   |
      | 性別                 | select/radio  | 是   |
      | 年齡                 | text          | 是   |
      | 是否結育             | select/radio  | 是   |
      | 晶片號碼             | text          | 否   |
      | 未登記身分識別方式   | text          | 否   |
    And 寵物個性應提供多選勾選：親人、不會咬人、不會咬狗貓、容易緊張、親狗、會咬人、會咬狗貓、有攻擊性
    And 身體狀態檢視應提供：眼睛、耳朵、牙齒、四肢、皮膚（正常/異常）、皮毛（正常/打結/跳蚤壁蝨）
    And 病史應提供多選勾選（含「其它」自由輸入）

  @frontend @unit-test
  Scenario: 前端 - 客戶新增多隻寵物
    Given 使用者在客戶資料填寫頁
    When 客戶填寫第一隻寵物「Lucky」
    And 客戶點擊「新增寵物」按鈕
    Then 頁面應新增一組空白寵物表單
    And 客戶可填寫第二隻寵物「Mimi」

  # ===================================================================
  # 前端 - 送出資料
  # ===================================================================

  @frontend @unit-test
  Scenario: 前端 - 客戶成功送出資料
    Given 客戶已完整填寫飼主資料與至少一隻寵物資料
    When 客戶按下「送出資料」按鈕
    Then 前端應先呼叫 POST "/api/owners" 建立飼主
    And API 回傳 201 後取得新飼主的 id
    And 前端應再呼叫 POST "/api/pets" 建立寵物，帶入 ownerId
    And 所有 API 成功後應顯示「資料送出完成」的提示
    And 頁面不應顯示其他客戶資料

  @frontend @unit-test
  Scenario Outline: 前端 - 飼主必填欄位未填時拒絕送出
    Given 客戶在客戶資料填寫頁
    When 客戶未填寫 "<欄位>" 但其他必填欄位皆有值
    And 客戶按下送出資料按鈕
    Then 表單應顯示 "<欄位>" 為必填的驗證錯誤
    And 不應呼叫任何 API
    Examples:
      | 欄位                   |
      | 姓名                   |
      | 身分證字號             |
      | 聯絡電話               |
      | 通訊地址               |
      | 緊急聯絡人             |
      | 緊急聯絡人電話         |
      | 緊急聯絡人與飼主關係   |

  @frontend @unit-test
  Scenario Outline: 前端 - 寵物必填欄位未填時拒絕送出
    Given 客戶已完整填寫飼主資料
    When 客戶未填寫寵物的 "<欄位>" 但其他寵物必填欄位皆有值
    And 客戶按下送出資料按鈕
    Then 表單應顯示寵物 "<欄位>" 為必填的驗證錯誤
    And 不應呼叫任何 API
    Examples:
      | 欄位       |
      | 名稱       |
      | 種類       |
      | 品種       |
      | 性別       |
      | 年齡       |
      | 是否結育   |

  @frontend @unit-test
  Scenario: 前端 - 未填寫任何寵物時拒絕送出
    Given 客戶已完整填寫飼主資料但未填寫任何寵物
    When 客戶按下送出資料按鈕
    Then 應顯示「至少需填寫一隻寵物」的驗證錯誤

  # ===================================================================
  # 前端 - 畫面限制
  # ===================================================================

  @frontend @unit-test
  Scenario: 前端 - 客戶填寫頁不顯示其他客戶資料
    Given 系統中已有飼主「李小花」
    When 使用者進入客戶資料填寫頁
    Then 頁面不應顯示任何既有飼主列表
    And 頁面不應顯示「李小花」的資料

  @frontend @unit-test
  Scenario: 前端 - 客戶填寫頁不提供店內管理功能
    Given 使用者在客戶資料填寫頁
    Then 頁面不應提供刪除資料的按鈕
    And 頁面不應提供瀏覽全部客戶的連結
    And 頁面不應提供預約管理功能
    And 頁面不應提供行事曆功能
    And 頁面不應提供 PDF 產生功能

  @frontend @unit-test
  Scenario: 前端 - 客戶填寫頁提供返回店家操作畫面的入口
    Given 使用者在客戶資料填寫頁
    Then 頁面應顯示「返回店家操作」的連結或按鈕
    When 使用者點擊返回
    Then 頁面應導向店家管理首頁

  # ===================================================================
  # 後端 - 客戶資料保存
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 客戶填寫頁送出的資料與一般新增飼主使用相同 API
    When 呼叫 POST "/api/owners" 帶入客戶填寫的飼主資料
    Then 回應狀態碼應為 201
    And 飼主資料應正常保存至 owners.json

  @backend @unit-test
  Scenario: 後端 - 客戶填寫的多隻寵物都正確關聯到飼主
    Given 已透過 POST "/api/owners" 建立飼主 "owner_new"
    When 呼叫 POST "/api/pets" 帶入 ownerId "owner_new" 和寵物「Lucky」
    And 呼叫 POST "/api/pets" 帶入 ownerId "owner_new" 和寵物「Mimi」
    Then pets.json 中應有兩筆寵物，ownerId 均為 "owner_new"
