# language: zh-TW
# Generated by sa-expert
# Source: pm/features/daily_appointment_list.feature
# Project scan date: 2026-04-16

Feature: 當日預約列表
  對應模組：前端 Vue 元件（DailyAppointmentList）+ 後端預約 API
  API：GET /api/appointments/date/:date

  Background:
    Given 系統已啟動且資料目錄已建立
    And appointments.json 中已有以下 2026-04-20 的預約：
      | id       | petId   | ownerId   | time  | status |
      | appt_001 | pet_002 | owner_002 | 10:00 | 已預約 |
      | appt_002 | pet_001 | owner_001 | 14:00 | 已預約 |

  # ===================================================================
  # 後端 - 取得指定日期預約
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 取得指定日期的預約列表（含關聯資料）
    When 呼叫 GET "/api/appointments/date/2026-04-20"
    Then 回應狀態碼應為 200
    And 回應 JSON 陣列應包含 2 筆預約
    And 每筆預約應包含以下欄位：
      | 欄位               | 說明                           |
      | id                 | 預約 ID                        |
      | date               | 預約日期                       |
      | time               | 預約時間                       |
      | status             | 預約狀態                       |
      | petName            | 寵物名稱（關聯 pets.json）     |
      | ownerName          | 飼主姓名（關聯 owners.json）   |
      | ownerPhone         | 飼主電話（關聯 owners.json）   |
      | hasContract        | 是否已產生契約                 |
    And 回應應依 time 升序排列

  @backend @unit-test
  Scenario: 後端 - 查詢無預約的日期
    When 呼叫 GET "/api/appointments/date/2026-04-21"
    Then 回應狀態碼應為 200
    And 回應 JSON 陣列應為空

  # ===================================================================
  # 前端 - 列表顯示
  # ===================================================================

  @frontend @unit-test
  Scenario: 前端 - 當日預約列表顯示所有欄位
    Given 使用者導向 "/appointments/daily/2026-04-20"
    When 前端呼叫 GET "/api/appointments/date/2026-04-20" 並取得資料
    Then 列表應顯示以下欄位：預約時間、寵物名稱、飼主姓名、聯絡電話、預約狀態、是否已產生契約
    And 列表第一筆應為 10:00 的「Mimi」
    And 列表第二筆應為 14:00 的「Lucky」

  @frontend @unit-test
  Scenario: 前端 - 顯示日期標題
    Given 使用者導向 "/appointments/daily/2026-04-20"
    Then 頁面應顯示日期標題 "2026-04-20"

  @frontend @unit-test
  Scenario: 前端 - 點擊預約導向美容服務資料頁
    Given 使用者在 2026-04-20 的當日預約列表
    When 使用者點擊「Lucky」的預約列
    Then 頁面應導向 Lucky 的美容服務資料輸入頁（帶入 appointmentId）

  @frontend @unit-test
  Scenario: 前端 - 已取消預約顯示狀態標示與取消原因
    Given appointments.json 中 "appt_002" 的 status 為 "已取消"，cancelReason 為 "飼主臨時有事"
    When 使用者開啟 2026-04-20 的當日預約列表
    Then 「Lucky」的預約狀態應顯示為「已取消」樣式
    And 應顯示取消原因「飼主臨時有事」

  @frontend @unit-test
  Scenario: 前端 - 已產生契約的預約顯示標示與下載入口
    Given "appt_001" 的 hasContract 為 true
    When 使用者開啟 2026-04-20 的當日預約列表
    Then 「Mimi」的預約應顯示已產生契約的圖示或標示
    And 應提供下載契約 PDF 的連結

  @frontend @unit-test
  Scenario: 前端 - 當日無預約時顯示空狀態
    Given API 回傳空陣列
    When 使用者開啟 2026-04-21 的當日預約列表
    Then 列表應顯示「當日無預約」的提示訊息

  @frontend @unit-test
  Scenario: 前端 - 已完成預約顯示已完成狀態
    Given "appt_001" 的 status 為 "已完成"
    When 使用者開啟 2026-04-20 的當日預約列表
    Then 「Mimi」的預約狀態應顯示為「已完成」
