# language: zh-TW
# Generated by sa-expert
# Source: pm/features/data_backup.feature
# Project scan date: 2026-04-16

Feature: 資料備份與匯出
  對應模組：後端 BackupController / BackupService
  API 基礎路徑：/api/backup

  Background:
    Given 系統已啟動且資料目錄已建立

  # ===================================================================
  # 後端 - 一鍵備份
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 成功執行一鍵備份
    Given data/ 目錄中已有 owners.json、pets.json、appointments.json、grooming-records.json、settings.json
    And generated-contracts/ 目錄中已有 PDF 檔案
    When 呼叫 POST "/api/backup"
    Then 回應狀態碼應為 200
    And 回應 JSON 應包含：
      | 欄位           | 說明                               |
      | backupPath     | 備份檔案路徑                       |
      | timestamp      | 備份時間戳記（ISO 8601）           |
      | filesCount     | 備份的檔案數量                     |
    And 備份目錄下應存在新的備份檔案（含時間戳記）
    And 備份應包含所有 JSON 資料檔案
    And 備份應包含所有已產生的契約 PDF 檔案

  @backend @unit-test
  Scenario: 後端 - 備份檔案包含時間戳記避免覆蓋舊備份
    Given 已存在一份備份檔案（時間戳記 2026-04-16T10:00:00）
    When 呼叫 POST "/api/backup"
    Then 新備份檔案的時間戳記應與舊備份不同
    And 舊備份檔案不應被覆蓋

  @backend @unit-test
  Scenario: 後端 - 系統中無任何資料時仍可執行備份
    Given data/ 目錄中的 JSON 檔案內容均為空陣列
    When 呼叫 POST "/api/backup"
    Then 回應狀態碼應為 200
    And 備份應包含空的 JSON 資料檔案

  @backend @unit-test
  Scenario: 後端 - 備份目錄無寫入權限時回傳 500
    Given 備份目錄沒有寫入權限
    When 呼叫 POST "/api/backup"
    Then 回應狀態碼應為 500
    And 回應 JSON 的 error.message 應包含 "無法寫入備份目錄"

  # ===================================================================
  # 後端 - 備份列表
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 取得備份檔案列表
    Given 備份目錄下已有多份備份檔案
    When 呼叫 GET "/api/backup/list"
    Then 回應狀態碼應為 200
    And 回應 JSON 陣列每筆應包含：
      | 欄位           | 說明                 |
      | fileName       | 備份檔案名稱         |
      | timestamp      | 備份時間戳記         |
      | size           | 檔案大小             |

  @backend @unit-test
  Scenario: 後端 - 無備份時回傳空列表
    Given 備份目錄下沒有任何備份檔案
    When 呼叫 GET "/api/backup/list"
    Then 回應狀態碼應為 200
    And 回應 JSON 陣列應為空

  # ===================================================================
  # 前端 - 備份介面
  # ===================================================================

  @frontend @unit-test
  Scenario: 前端 - 資料備份頁顯示備份按鈕與列表
    Given 使用者導向資料備份頁面
    Then 頁面應顯示一鍵備份按鈕
    And 頁面應顯示備份檔案列表（呼叫 GET "/api/backup/list"）
    And 頁面應顯示備份狀態提示區域

  @frontend @unit-test
  Scenario: 前端 - 按下一鍵備份後呼叫 API
    Given 使用者在資料備份頁面
    When 使用者按下一鍵備份按鈕
    Then 前端應呼叫 POST "/api/backup"
    And API 回應 200 後應顯示備份成功提示
    And 備份檔案列表應重新載入

  @frontend @unit-test
  Scenario: 前端 - 備份失敗時顯示錯誤訊息
    Given 使用者按下一鍵備份按鈕
    When API 回傳 500 且 error.message 為 "無法寫入備份目錄"
    Then 頁面應顯示「無法寫入備份目錄」的錯誤訊息
    And 應提示使用者調整目錄或權限

  @frontend @unit-test
  Scenario: 前端 - 備份列表為空時顯示提示
    Given API 回傳空備份列表
    Then 頁面應顯示「尚無備份檔案」的提示訊息
