# language: zh-TW
# Generated by sa-expert
# Source: pm/features/electronic_signature.feature
# Project scan date: 2026-04-16

Feature: 電子簽名
  對應模組：前端 SignaturePad 元件 + 後端 ContractController / ContractService / PdfGenerator
  API：POST /api/contracts/:recordId/sign

  Background:
    Given 系統已啟動且資料目錄已建立
    And grooming-records.json 中已有紀錄 "rec_001" 且已產生契約 PDF

  # ===================================================================
  # 後端 - 簽名嵌入 PDF
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 成功上傳簽名並嵌入 PDF
    When 呼叫 POST "/api/contracts/rec_001/sign" 並帶入簽名圖片（base64）：
      """
      {
        "signatureImage": "data:image/png;base64,iVBORw0KGgo..."
      }
      """
    Then 回應狀態碼應為 200
    And 回應 JSON 應包含更新後的 contractPath
    And PDF 第 3 頁甲方簽章位置應嵌入簽名圖片
    And PDF 第 4 頁飼主簽名位置應嵌入簽名圖片
    And 嵌入簽名後的 PDF 應重新保存至 generated-contracts/

  @backend @unit-test
  Scenario: 後端 - 簽名圖片未提供時回傳 400
    When 呼叫 POST "/api/contracts/rec_001/sign" 帶入空的 signatureImage
    Then 回應狀態碼應為 400
    And 回應 JSON 的 error.message 應包含 "簽名圖片" 為必填

  @backend @unit-test
  Scenario: 後端 - 契約 PDF 不存在時回傳 404
    Given grooming-records.json 中 "rec_002" 尚未產生契約 PDF
    When 呼叫 POST "/api/contracts/rec_002/sign" 帶入簽名圖片
    Then 回應狀態碼應為 404
    And 回應 JSON 的 error.message 應包含 "契約 PDF 不存在，請先產生契約"

  @backend @unit-test
  Scenario: 後端 - PdfGenerator 將簽名嵌入第 3 頁甲方簽章位置
    Given 已有契約 PDF 檔案
    When PdfGenerator 嵌入簽名圖片至第 3 頁
    Then 簽名圖片應繪製在第 3 頁甲方簽章的座標位置

  @backend @unit-test
  Scenario: 後端 - PdfGenerator 將簽名嵌入第 4 頁飼主簽名位置
    Given 已有契約 PDF 檔案
    When PdfGenerator 嵌入簽名圖片至第 4 頁
    Then 簽名圖片應繪製在第 4 頁飼主簽名的座標位置

  # ===================================================================
  # 前端 - 簽名板元件
  # ===================================================================

  @frontend @unit-test
  Scenario: 前端 - 簽名板元件顯示
    Given 使用者導向電子簽名頁面
    Then 頁面應顯示 SignaturePad 簽名板元件
    And 簽名板應支援滑鼠繪製（mousedown/mousemove/mouseup 事件）
    And 簽名板應支援觸控繪製（touchstart/touchmove/touchend 事件）

  @frontend @unit-test
  Scenario: 前端 - 飼主在簽名板上手寫簽名
    Given 使用者在電子簽名頁面
    When 飼主在簽名板上移動滑鼠繪製簽名
    Then 簽名板的 canvas 應即時顯示簽名軌跡

  @frontend @unit-test
  Scenario: 前端 - 清除簽名重新簽名
    Given 飼主已在簽名板上完成簽名
    When 飼主按下「清除重簽」按鈕
    Then 簽名板的 canvas 應清空
    And 「確認簽名」按鈕應維持可點擊狀態

  @frontend @unit-test
  Scenario: 前端 - 確認簽名後呼叫 API
    Given 飼主已在簽名板上完成簽名
    When 飼主按下「確認簽名」按鈕
    Then 前端應將 canvas 轉為 base64 PNG 格式
    And 前端應呼叫 POST "/api/contracts/rec_001/sign" 帶入 signatureImage
    And API 回應 200 後應顯示簽名完成的提示

  @frontend @unit-test
  Scenario: 前端 - 簽名預覽
    Given 飼主已在簽名板上完成簽名
    When 飼主查看簽名預覽區域
    Then 應顯示簽名的縮圖預覽

  @frontend @unit-test
  Scenario: 前端 - 未簽名就按確認時顯示提示
    Given 簽名板上尚無任何簽名（canvas 為空白）
    When 飼主按下「確認簽名」按鈕
    Then 應顯示「請先完成簽名」的提示訊息
    And 不應呼叫 POST "/api/contracts/:recordId/sign" API

  @frontend @unit-test
  Scenario: 前端 - 簽名上傳失敗時顯示錯誤
    Given 飼主已在簽名板上完成簽名
    When 前端呼叫 API 但回傳錯誤
    Then 應顯示「簽名上傳失敗」的錯誤訊息
    And 飼主可重新嘗試確認簽名

  @frontend @unit-test
  Scenario: 前端 - 契約 PDF 未產生時不顯示簽名入口
    Given 美容紀錄 "rec_002" 尚未產生契約 PDF
    When 使用者在美容服務資料頁查看 "rec_002"
    Then 電子簽名按鈕應為禁用狀態或隱藏
    And 應提示「請先產生契約 PDF」
