# language: zh-TW
# Generated by sa-expert
# Source: pm/features/grooming_record.feature
# Project scan date: 2026-04-16

Feature: 美容紀錄
  對應模組：後端 Controller / Service / Repository 三層式架構
  資料實體：GroomingRecord -> JSON 檔案 data/grooming-records.json
  API 基礎路徑：/api/grooming-records

  Background:
    Given 系統已啟動且資料目錄已建立
    And owners.json 中已有飼主 "owner_001"（王小明），isStoredValueCustomer: true, storedValueBalance: 5000
    And pets.json 中已有寵物 "pet_001"（Lucky）關聯 "owner_001"
    And appointments.json 中已有預約 "appt_001"，petId: "pet_001", ownerId: "owner_001", date: "2026-04-20", time: "14:00", status: "已預約"

  # ===================================================================
  # 後端 - 建立美容紀錄
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 成功建立美容紀錄
    When 呼叫 POST "/api/grooming-records" 並帶入以下 JSON：
      """
      {
        "appointmentId": "appt_001",
        "serviceDate": "2026-04-20",
        "serviceTime": "14:00",
        "services": [
          { "item": "洗澡", "price": 500 }
        ],
        "physicalExamination": {
          "eyes": "正常", "ears": "正常", "teeth": "正常",
          "limbs": "正常", "skin": "正常", "fur": "正常"
        },
        "medicalHistory": [],
        "medicalHistoryOther": "",
        "personality": ["親人", "不會咬人", "不會咬狗貓"]
      }
      """
    Then 回應狀態碼應為 201
    And 回應 JSON 應包含自動產生的 "id" 欄位（格式如 "rec_xxx"）
    And 回應 JSON 的 "appointmentId" 應為 "appt_001"
    And 回應 JSON 的 "storedValueDeduction" 應為 500
    And 回應 JSON 的 "cashPayment" 應為 0
    And 回應 JSON 的 "createdAt" 應為 ISO 8601 格式
    And grooming-records.json 中應存在該筆紀錄
    And owners.json 中 "owner_001" 的 storedValueBalance 應更新為 4500

  @backend @unit-test
  Scenario: 後端 - 美容項目為固定選單（洗澡、美容、其他）
    When 呼叫 POST "/api/grooming-records" 帶入 services 包含無效項目 "染色"
    Then 回應狀態碼應為 400
    And 回應 JSON 的 error.message 應包含 "美容項目" 不合法

  @backend @unit-test
  Scenario: 後端 - 多個美容項目並輸入各項費用
    When 呼叫 POST "/api/grooming-records" 帶入以下 services：
      """
      [
        { "item": "洗澡", "price": 500 },
        { "item": "美容", "price": 800 }
      ]
      """
    Then 回應狀態碼應為 201
    And 回應 JSON 的 services 應包含洗澡 500 和美容 800

  # ===================================================================
  # 後端 - 儲值金額扣款計算（Service 層）
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 儲值型客戶餘額充足時全額扣除
    Given owners.json 中 "owner_001" storedValueBalance 為 5000
    When 呼叫 POST "/api/grooming-records" 帶入總費用 500
    Then 回應 JSON 的 "storedValueDeduction" 應為 500
    And 回應 JSON 的 "cashPayment" 應為 0
    And owners.json 中 "owner_001" storedValueBalance 應為 4500

  @backend @unit-test
  Scenario: 後端 - 儲值型客戶餘額不足時扣完儲值金差額現金支付
    Given owners.json 中 "owner_001" storedValueBalance 為 300
    When 呼叫 POST "/api/grooming-records" 帶入總費用 800
    Then 回應 JSON 的 "storedValueDeduction" 應為 300
    And 回應 JSON 的 "cashPayment" 應為 500
    And owners.json 中 "owner_001" storedValueBalance 應為 0

  @backend @unit-test
  Scenario: 後端 - 儲值型客戶餘額剛好等於費用
    Given owners.json 中 "owner_001" storedValueBalance 為 800
    When 呼叫 POST "/api/grooming-records" 帶入總費用 800
    Then 回應 JSON 的 "storedValueDeduction" 應為 800
    And 回應 JSON 的 "cashPayment" 應為 0
    And owners.json 中 "owner_001" storedValueBalance 應為 0

  @backend @unit-test
  Scenario: 後端 - 非儲值型客戶不計算儲值扣款
    Given owners.json 中 "owner_002" isStoredValueCustomer 為 false
    And pets.json 中有 "pet_002" 關聯 "owner_002"
    And appointments.json 中有 "appt_002" 關聯 "pet_002"
    When 呼叫 POST "/api/grooming-records" 帶入 appointmentId "appt_002" 且總費用 500
    Then 回應 JSON 的 "storedValueDeduction" 應為 0 或 null
    And 回應 JSON 的 "cashPayment" 應為 500

  # ===================================================================
  # 後端 - 寵物狀態與備註
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 建立美容紀錄時更新寵物身體狀態
    When 呼叫 POST "/api/grooming-records" 帶入 physicalExamination.skin 為 "異常"、fur 為 "打結"
    Then 回應狀態碼應為 201
    And 回應 JSON 的 physicalExamination.skin 應為 "異常"
    And 回應 JSON 的 physicalExamination.fur 應為 "打結"

  @backend @unit-test
  Scenario: 後端 - 建立美容紀錄時帶入選填欄位
    When 呼叫 POST "/api/grooming-records" 帶入以下選填欄位：
      """
      {
        "ownerNotes": "寵物最近食慾不振",
        "shopNotes": "需要特別注意皮膚狀態",
        "otherNotes": "客戶要求保留尾巴毛長"
      }
      """
    Then 回應狀態碼應為 201
    And 回應 JSON 應包含上述三個選填欄位

  # ===================================================================
  # 後端 - 更新美容紀錄
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 成功更新已保存的美容紀錄
    Given grooming-records.json 中已有紀錄 "rec_001"
    When 呼叫 PUT "/api/grooming-records/rec_001" 修改 services[0].price 為 600
    Then 回應狀態碼應為 200
    And 回應 JSON 的 "updatedAt" 應晚於原始值

  # ===================================================================
  # 後端 - 產生契約前檢查
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 美容紀錄未建立時無法產生契約
    When 呼叫 POST "/api/contracts/generate" 帶入不存在的 recordId
    Then 回應狀態碼應為 404
    And 回應 JSON 的 error.message 應包含 "查無美容紀錄"

  # ===================================================================
  # 前端 - 自動帶出資料
  # ===================================================================

  @frontend @unit-test
  Scenario: 前端 - 美容服務資料頁自動帶出飼主與寵物資料
    Given 使用者導向美容服務資料頁，帶入 appointmentId "appt_001"
    When 頁面載入時呼叫以下 API：
      | API                              | 用途             |
      | GET /api/appointments/appt_001   | 取得預約資料     |
      | GET /api/owners/owner_001        | 取得飼主資料     |
      | GET /api/pets/pet_001            | 取得寵物資料     |
    Then 頁面應自動顯示飼主姓名、電話、地址、身分證字號、緊急聯絡人
    And 頁面應自動顯示寵物名稱、種類、品種、性別、年齡、結育狀態
    And 頁面應自動帶入寵物個性勾選、身體狀態檢視、病史勾選

  @frontend @unit-test
  Scenario: 前端 - 美容項目固定選單顯示
    Given 使用者在美容服務資料頁
    Then 美容項目區塊應顯示固定選項：洗澡、美容、其他
    And 每個選項旁應有費用輸入欄位

  @frontend @unit-test
  Scenario: 前端 - 儲值型客戶自動計算扣款顯示
    Given 飼主 "owner_001" isStoredValueCustomer 為 true，storedValueBalance 為 5000
    When 使用者勾選「洗澡」並輸入費用 500
    Then 頁面應自動顯示儲值金額扣款 500
    And 頁面應自動顯示現金支付金額 0
    And 頁面應自動顯示扣款後儲值餘額 4500

  @frontend @unit-test
  Scenario: 前端 - 非儲值型客戶不顯示儲值扣款
    Given 飼主 "owner_002" isStoredValueCustomer 為 false
    When 使用者在美容服務資料頁
    Then 儲值金額扣款區塊應隱藏或顯示為空

  @frontend @unit-test
  Scenario: 前端 - 保存美容紀錄成功
    Given 使用者已填寫完整美容服務資料
    When 使用者按下保存按鈕
    Then 前端應呼叫 POST "/api/grooming-records" 帶入完整資料
    And API 回應 201 後應顯示保存成功訊息

  @frontend @unit-test
  Scenario: 前端 - 未選擇美容項目時不允許產生契約
    Given 使用者在美容服務資料頁
    And 使用者未勾選任何美容項目
    When 使用者按下產生契約按鈕
    Then 應顯示「請至少選擇一個美容項目」的驗證錯誤
    And 不應呼叫 POST "/api/contracts/generate" API
