# language: zh-TW
# Generated by sa-expert
# Source: pm/features/owner_management.feature
# Project scan date: 2026-04-16

Feature: 飼主管理
  對應模組：後端 Controller / Service / Repository 三層式架構
  資料實體：Owner -> JSON 檔案 data/owners.json
  API 基礎路徑：/api/owners

  Background:
    Given 系統已啟動且資料目錄已建立
    And JSON 檔案 "data/owners.json" 存在且格式正確

  # ===================================================================
  # 新增飼主
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 成功新增飼主 - 所有必填欄位皆填寫
    Given owners.json 中無任何飼主資料
    When 呼叫 POST "/api/owners" 並帶入以下 JSON：
      """
      {
        "name": "王小明",
        "nationalId": "A123456789",
        "phone": "0912345678",
        "address": "桃園市桃園區中正路1號",
        "emergencyContactName": "王太太",
        "emergencyContactPhone": "0987654321",
        "emergencyContactRelationship": "配偶"
      }
      """
    Then 回應狀態碼應為 201
    And 回應 JSON 應包含自動產生的 "id" 欄位（格式如 "owner_xxx"）
    And 回應 JSON 的 "createdAt" 應為 ISO 8601 格式
    And 回應 JSON 的 "updatedAt" 應為 ISO 8601 格式
    And owners.json 中應存在一筆 name 為 "王小明" 的飼主資料

  @backend @unit-test
  Scenario Outline: 後端 - 新增飼主時必填欄位未填 - 回傳 400
    When 呼叫 POST "/api/owners" 並帶入缺少 "<欄位名稱>" 的 JSON
    Then 回應狀態碼應為 400
    And 回應 JSON 的 error.message 應包含 "<欄位名稱>" 為必填
    And owners.json 不應新增任何資料
    Examples:
      | 欄位名稱                     |
      | name                         |
      | nationalId                   |
      | phone                        |
      | address                      |
      | emergencyContactName         |
      | emergencyContactPhone        |
      | emergencyContactRelationship |

  @backend @unit-test
  Scenario: 後端 - 新增飼主時填寫指定獸醫院資訊
    When 呼叫 POST "/api/owners" 並帶入以下 JSON：
      """
      {
        "name": "王小明",
        "nationalId": "A123456789",
        "phone": "0912345678",
        "address": "桃園市桃園區中正路1號",
        "emergencyContactName": "王太太",
        "emergencyContactPhone": "0987654321",
        "emergencyContactRelationship": "配偶",
        "preferredAnimalHospital": "仁愛動物醫院",
        "preferredAnimalHospitalPhone": "03-1234567",
        "preferredAnimalHospitalAddress": "桃園市中壢區中正路100號"
      }
      """
    Then 回應狀態碼應為 201
    And 回應 JSON 的 "preferredAnimalHospital" 應為 "仁愛動物醫院"

  @backend @unit-test
  Scenario: 後端 - 新增飼主時未填寫獸醫院資訊 - 欄位為空
    When 呼叫 POST "/api/owners" 帶入所有必填欄位但不含獸醫院資訊
    Then 回應狀態碼應為 201
    And 回應 JSON 的 "preferredAnimalHospital" 應為空字串或 null

  @backend @unit-test
  Scenario: 後端 - 新增飼主時填寫備註
    When 呼叫 POST "/api/owners" 帶入所有必填欄位且 note 為 "VIP客戶，每月固定來洗澡"
    Then 回應狀態碼應為 201
    And 回應 JSON 的 "note" 應為 "VIP客戶，每月固定來洗澡"

  @frontend @unit-test
  Scenario: 前端 - 新增飼主表單必填檢查
    Given 使用者在飼主新增頁面
    When 使用者未填寫任何欄位直接按下保存按鈕
    Then 表單應顯示所有必填欄位的驗證錯誤訊息
    And 不應呼叫 POST "/api/owners" API

  @frontend @unit-test
  Scenario: 前端 - 新增飼主成功後導向飼主列表
    Given 使用者在飼主新增頁面
    When 使用者填寫所有必填欄位並按下保存按鈕
    Then 前端應呼叫 POST "/api/owners" 並帶入表單資料
    And API 回應 201 後應顯示保存成功訊息
    And 頁面應導向飼主列表或飼主詳細頁

  # ===================================================================
  # 編輯飼主
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 成功編輯飼主資料
    Given owners.json 中已有 id 為 "owner_001" 的飼主「王小明」
    When 呼叫 PUT "/api/owners/owner_001" 並帶入以下 JSON：
      """
      {
        "name": "王小明",
        "nationalId": "A123456789",
        "phone": "0911111111",
        "address": "桃園市桃園區中正路1號",
        "emergencyContactName": "王太太",
        "emergencyContactPhone": "0987654321",
        "emergencyContactRelationship": "配偶"
      }
      """
    Then 回應狀態碼應為 200
    And 回應 JSON 的 "phone" 應為 "0911111111"
    And 回應 JSON 的 "updatedAt" 應晚於 "createdAt"
    And owners.json 中 "owner_001" 的 phone 應為 "0911111111"

  @backend @unit-test
  Scenario: 後端 - 編輯飼主時清除必填欄位 - 回傳 400
    Given owners.json 中已有 id 為 "owner_001" 的飼主「王小明」
    When 呼叫 PUT "/api/owners/owner_001" 並帶入 name 為空字串的 JSON
    Then 回應狀態碼應為 400
    And 回應 JSON 的 error.message 應包含 "name" 為必填

  @backend @unit-test
  Scenario: 後端 - 編輯不存在的飼主 - 回傳 404
    When 呼叫 PUT "/api/owners/owner_999" 並帶入合法 JSON
    Then 回應狀態碼應為 404
    And 回應 JSON 的 error.message 應包含 "查無此飼主"

  @backend @unit-test
  Scenario: 後端 - 編輯飼主後關聯的寵物與預約仍維持關聯
    Given owners.json 中已有飼主 "owner_001"
    And pets.json 中已有寵物 "pet_001" 關聯 "owner_001"
    And appointments.json 中已有預約 "appt_001" 關聯 "owner_001" 和 "pet_001"
    When 呼叫 PUT "/api/owners/owner_001" 修改通訊地址
    Then 回應狀態碼應為 200
    And pets.json 中 "pet_001" 的 ownerId 仍為 "owner_001"
    And appointments.json 中 "appt_001" 的 ownerId 仍為 "owner_001"

  @frontend @unit-test
  Scenario: 前端 - 編輯飼主頁面載入時帶入現有資料
    Given 使用者在飼主編輯頁面，飼主 ID 為 "owner_001"
    When 頁面載入時呼叫 GET "/api/owners/owner_001"
    Then 表單各欄位應填入 API 回傳的飼主資料

  # ===================================================================
  # 查詢飼主
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 依姓名查詢飼主
    Given owners.json 中已有飼主「王小明」和「李小花」
    When 呼叫 GET "/api/owners?keyword=王"
    Then 回應狀態碼應為 200
    And 回應 JSON 陣列應包含 name 為 "王小明" 的飼主
    And 回應 JSON 陣列不應包含 name 為 "李小花" 的飼主

  @backend @unit-test
  Scenario: 後端 - 依電話查詢飼主
    Given owners.json 中已有飼主「王小明」電話為 "0912345678"
    When 呼叫 GET "/api/owners?keyword=0912"
    Then 回應狀態碼應為 200
    And 回應 JSON 陣列應包含 phone 為 "0912345678" 的飼主

  @backend @unit-test
  Scenario: 後端 - 查詢無結果
    Given owners.json 中已有飼主「王小明」
    When 呼叫 GET "/api/owners?keyword=張"
    Then 回應狀態碼應為 200
    And 回應 JSON 陣列應為空陣列

  @frontend @unit-test
  Scenario: 前端 - 搜尋飼主並顯示結果
    Given 使用者在飼主列表頁面
    When 使用者在搜尋欄輸入 "王" 並觸發搜尋
    Then 前端應呼叫 GET "/api/owners?keyword=王"
    And 列表應顯示符合條件的飼主姓名、電話及寵物摘要

  @frontend @unit-test
  Scenario: 前端 - 搜尋無結果時顯示提示
    Given 使用者在飼主列表頁面
    When API 回傳空陣列
    Then 頁面應顯示「查無資料」的提示訊息

  # ===================================================================
  # 儲值金額管理
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 開啟飼主儲值型客戶狀態
    Given owners.json 中已有飼主 "owner_001"，isStoredValueCustomer 為 false
    When 呼叫 PUT "/api/owners/owner_001" 帶入 isStoredValueCustomer 為 true
    Then 回應狀態碼應為 200
    And 回應 JSON 的 "isStoredValueCustomer" 應為 true

  @backend @unit-test
  Scenario: 後端 - 關閉飼主儲值型客戶狀態
    Given owners.json 中已有飼主 "owner_001"，isStoredValueCustomer 為 true，storedValueBalance 為 0
    When 呼叫 PUT "/api/owners/owner_001" 帶入 isStoredValueCustomer 為 false
    Then 回應狀態碼應為 200
    And 回應 JSON 的 "isStoredValueCustomer" 應為 false

  @backend @unit-test
  Scenario: 後端 - 手動更新儲值金額
    Given owners.json 中已有飼主 "owner_001"，isStoredValueCustomer 為 true，storedValueBalance 為 3000
    When 呼叫 PUT "/api/owners/owner_001" 帶入 storedValueBalance 為 8000
    Then 回應狀態碼應為 200
    And 回應 JSON 的 "storedValueBalance" 應為 8000
    And owners.json 中 "owner_001" 的 storedValueBalance 應為 8000

  @backend @unit-test
  Scenario: 後端 - 儲值餘額不得設為負數
    Given owners.json 中已有飼主 "owner_001"，isStoredValueCustomer 為 true
    When 呼叫 PUT "/api/owners/owner_001" 帶入 storedValueBalance 為 -100
    Then 回應狀態碼應為 400
    And 回應 JSON 的 error.message 應包含 "儲值餘額不得小於 0"
    And owners.json 中 "owner_001" 的 storedValueBalance 不應被更新

  @frontend @unit-test
  Scenario: 前端 - 儲值金額欄位驗證不得為負數
    Given 使用者在飼主編輯頁面
    When 使用者在儲值金額欄位輸入 -100
    Then 表單應顯示儲值餘額不得小於 0 的驗證錯誤
    And 不應呼叫 PUT "/api/owners/:ownerId" API
