# language: zh-TW
# Generated by sa-expert
# Source: pm/features/pet_management.feature
# Project scan date: 2026-04-16

Feature: 寵物管理
  對應模組：後端 Controller / Service / Repository 三層式架構
  資料實體：Pet -> JSON 檔案 data/pets.json
  API 基礎路徑：/api/pets, /api/owners/:ownerId/pets

  Background:
    Given 系統已啟動且資料目錄已建立
    And JSON 檔案 "data/owners.json" 中已有飼主 "owner_001"（王小明）
    And JSON 檔案 "data/pets.json" 存在且格式正確

  # ===================================================================
  # 新增寵物
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 成功新增寵物 - 所有必填欄位皆填寫
    When 呼叫 POST "/api/pets" 並帶入以下 JSON：
      """
      {
        "ownerId": "owner_001",
        "name": "Lucky",
        "species": "犬",
        "breed": "貴賓",
        "gender": "公",
        "age": "3歲",
        "isNeutered": true,
        "personality": ["親人", "不會咬人", "不會咬狗貓"],
        "physicalExamination": {
          "eyes": "正常",
          "ears": "正常",
          "teeth": "正常",
          "limbs": "正常",
          "skin": "正常",
          "fur": "正常"
        },
        "medicalHistory": [],
        "medicalHistoryOther": ""
      }
      """
    Then 回應狀態碼應為 201
    And 回應 JSON 應包含自動產生的 "id" 欄位（格式如 "pet_xxx"）
    And 回應 JSON 的 "ownerId" 應為 "owner_001"
    And 回應 JSON 的 "createdAt" 應為 ISO 8601 格式
    And pets.json 中應存在一筆 name 為 "Lucky" 的寵物資料

  @backend @unit-test
  Scenario: 後端 - 新增寵物未指定飼主 - 回傳 400
    When 呼叫 POST "/api/pets" 並帶入缺少 "ownerId" 的 JSON
    Then 回應狀態碼應為 400
    And 回應 JSON 的 error.message 應包含 "ownerId" 為必填

  @backend @unit-test
  Scenario: 後端 - 新增寵物指定不存在的飼主 - 回傳 404
    When 呼叫 POST "/api/pets" 並帶入 ownerId 為 "owner_999"
    Then 回應狀態碼應為 404
    And 回應 JSON 的 error.message 應包含 "查無此飼主"

  @backend @unit-test
  Scenario Outline: 後端 - 新增寵物時必填欄位未填 - 回傳 400
    When 呼叫 POST "/api/pets" 並帶入缺少 "<欄位名稱>" 的 JSON（其他必填欄位皆有值）
    Then 回應狀態碼應為 400
    And 回應 JSON 的 error.message 應包含 "<欄位名稱>" 為必填
    Examples:
      | 欄位名稱            |
      | name                |
      | species             |
      | breed               |
      | gender              |
      | age                 |
      | isNeutered          |
      | personality         |
      | physicalExamination |
      | medicalHistory      |

  @backend @unit-test
  Scenario: 後端 - 新增寵物時 personality 為空陣列 - 回傳 400
    When 呼叫 POST "/api/pets" 帶入 personality 為空陣列
    Then 回應狀態碼應為 400
    And 回應 JSON 的 error.message 應包含 "寵物個性" 為必填

  @backend @unit-test
  Scenario: 後端 - 新增寵物時帶入多個個性選項
    When 呼叫 POST "/api/pets" 帶入 personality 為 ["容易緊張", "會咬人", "有攻擊性"]
    Then 回應狀態碼應為 201
    And 回應 JSON 的 "personality" 應包含 "容易緊張"、"會咬人"、"有攻擊性"

  @backend @unit-test
  Scenario: 後端 - 新增寵物時帶入部分異常的身體狀態
    When 呼叫 POST "/api/pets" 帶入 physicalExamination 如下：
      """
      {
        "eyes": "正常",
        "ears": "異常",
        "teeth": "正常",
        "limbs": "正常",
        "skin": "異常",
        "fur": "打結"
      }
      """
    Then 回應狀態碼應為 201
    And 回應 JSON 的 physicalExamination.ears 應為 "異常"
    And 回應 JSON 的 physicalExamination.skin 應為 "異常"
    And 回應 JSON 的 physicalExamination.fur 應為 "打結"

  @backend @unit-test
  Scenario: 後端 - 新增寵物時帶入病史含「其它」
    When 呼叫 POST "/api/pets" 帶入 medicalHistory 為 ["心臟病", "氣喘", "其它"] 且 medicalHistoryOther 為 "長期皮膚過敏"
    Then 回應狀態碼應為 201
    And 回應 JSON 的 "medicalHistory" 應包含 "心臟病"、"氣喘"、"其它"
    And 回應 JSON 的 "medicalHistoryOther" 應為 "長期皮膚過敏"

  @backend @unit-test
  Scenario: 後端 - 新增寵物時帶入晶片號碼
    When 呼叫 POST "/api/pets" 帶入 chipNumber 為 "900000000012345"
    Then 回應狀態碼應為 201
    And 回應 JSON 的 "chipNumber" 應為 "900000000012345"

  @backend @unit-test
  Scenario: 後端 - 新增寵物時帶入未登記身分識別方式
    When 呼叫 POST "/api/pets" 帶入無 chipNumber 且 unregisteredIdMethod 為 "左耳有黑色記號"
    Then 回應狀態碼應為 201
    And 回應 JSON 的 "unregisteredIdMethod" 應為 "左耳有黑色記號"

  # ===================================================================
  # 取得飼主的寵物
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 取得飼主的寵物列表
    Given pets.json 中已有寵物 "pet_001"（Lucky）關聯 "owner_001"
    When 呼叫 GET "/api/owners/owner_001/pets"
    Then 回應狀態碼應為 200
    And 回應 JSON 陣列應包含 name 為 "Lucky" 的寵物

  # ===================================================================
  # 編輯寵物
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 成功編輯寵物資料
    Given pets.json 中已有寵物 "pet_001"（Lucky），age 為 "3歲"
    When 呼叫 PUT "/api/pets/pet_001" 帶入 age 為 "4歲"
    Then 回應狀態碼應為 200
    And 回應 JSON 的 "age" 應為 "4歲"
    And 回應 JSON 的 "updatedAt" 應晚於原始值
    And pets.json 中 "pet_001" 的 age 應為 "4歲"

  @backend @unit-test
  Scenario: 後端 - 編輯寵物的個性勾選
    Given pets.json 中已有寵物 "pet_001"，personality 為 ["親人", "不會咬人"]
    When 呼叫 PUT "/api/pets/pet_001" 帶入 personality 為 ["親人", "容易緊張"]
    Then 回應狀態碼應為 200
    And 回應 JSON 的 "personality" 應包含 "親人"、"容易緊張"
    And 回應 JSON 的 "personality" 不應包含 "不會咬人"

  @backend @unit-test
  Scenario: 後端 - 編輯寵物的身體狀態
    Given pets.json 中已有寵物 "pet_001"
    When 呼叫 PUT "/api/pets/pet_001" 帶入 physicalExamination.fur 為 "跳蚤壁蝨"
    Then 回應狀態碼應為 200
    And 回應 JSON 的 physicalExamination.fur 應為 "跳蚤壁蝨"

  @backend @unit-test
  Scenario: 後端 - 編輯寵物的結育狀態
    Given pets.json 中已有寵物 "pet_001"，isNeutered 為 false
    When 呼叫 PUT "/api/pets/pet_001" 帶入 isNeutered 為 true
    Then 回應狀態碼應為 200
    And 回應 JSON 的 "isNeutered" 應為 true

  @backend @unit-test
  Scenario: 後端 - 編輯不存在的寵物 - 回傳 404
    When 呼叫 PUT "/api/pets/pet_999" 並帶入合法 JSON
    Then 回應狀態碼應為 404

  @backend @unit-test
  Scenario: 後端 - 編輯寵物後既有預約與美容紀錄仍維持關聯
    Given pets.json 中已有寵物 "pet_001"
    And appointments.json 中已有預約 "appt_001" 關聯 "pet_001"
    And grooming-records.json 中已有美容紀錄 "rec_001" 關聯 "appt_001"
    When 呼叫 PUT "/api/pets/pet_001" 修改 age 為 "4歲"
    Then 回應狀態碼應為 200
    And appointments.json 中 "appt_001" 的 petId 仍為 "pet_001"
    And grooming-records.json 中 "rec_001" 的關聯仍完整

  @frontend @unit-test
  Scenario: 前端 - 新增寵物表單必填檢查
    Given 使用者在寵物新增頁面
    When 使用者未填寫任何欄位直接按下保存按鈕
    Then 表單應顯示名稱、種類、品種、性別、年齡、是否結育、寵物個性、身體狀態檢視、病史的驗證錯誤
    And 不應呼叫 POST "/api/pets" API

  @frontend @unit-test
  Scenario: 前端 - 寵物個性多選勾選元件
    Given 使用者在寵物表單頁面
    Then 寵物個性區塊應顯示以下選項：親人、不會咬人、不會咬狗貓、容易緊張、親狗、會咬人、會咬狗貓、有攻擊性
    And 使用者可多選勾選

  @frontend @unit-test
  Scenario: 前端 - 身體狀態檢視元件
    Given 使用者在寵物表單頁面
    Then 身體狀態區塊應顯示：眼睛、耳朵、牙齒、四肢、皮膚（選項：正常/異常）與皮毛（選項：正常/打結/跳蚤壁蝨）

  @frontend @unit-test
  Scenario: 前端 - 寵物病史多選勾選元件
    Given 使用者在寵物表單頁面
    Then 病史區塊應顯示以下選項：心臟病、氣喘、氣管塌陷、白內障、癲癇、心絲蟲、艾利希體、腹膜炎、腹積水、手術外傷未癒合、髖關節問題、骨折、腸炎、血便、血尿、懷孕、傳染性疾病、其它
    And 選擇「其它」時應出現自由輸入欄位
