# language: zh-TW
# Generated by sa-expert
# Source: pm/features/stored_value.feature
# Project scan date: 2026-04-16

Feature: 儲值金額完整流程
  對應模組：後端 OwnerService（儲值管理）+ GroomingRecordService（扣款計算）+ ContractService（PDF 帶入）
  資料實體：Owner.storedValueBalance, Owner.isStoredValueCustomer

  Background:
    Given 系統已啟動且資料目錄已建立

  # ===================================================================
  # 後端 - Service 層儲值扣款計算邏輯
  # ===================================================================

  @backend @unit-test
  Scenario Outline: 後端 - 儲值型客戶扣款計算（Service 層純邏輯測試）
    Given 儲值餘額為 <儲值餘額>
    And 本次費用合計為 <本次費用>
    When 呼叫 StoredValueService.calculate(balance, totalCost)
    Then 儲值扣款金額應為 <儲值扣款>
    And 現金支付金額應為 <現金支付>
    And 扣款後餘額應為 <扣款後餘額>
    Examples:
      | 儲值餘額 | 本次費用 | 儲值扣款 | 現金支付 | 扣款後餘額 |
      | 5000     | 500      | 500      | 0        | 4500       |
      | 5000     | 5000     | 5000     | 0        | 0          |
      | 300      | 800      | 300      | 500      | 0          |
      | 0        | 500      | 0        | 500      | 0          |
      | 1000     | 1000     | 1000     | 0        | 0          |
      | 100      | 100      | 100      | 0        | 0          |

  @backend @unit-test
  Scenario: 後端 - 儲值餘額不得小於 0（Service 層驗證）
    Given 儲值餘額為 200
    And 本次費用合計為 500
    When 呼叫 StoredValueService.calculate(200, 500)
    Then 儲值扣款金額應為 200
    And 扣款後餘額應為 0
    And 扣款後餘額不應小於 0

  @backend @unit-test
  Scenario: 後端 - 非儲值型客戶扣款計算回傳 0
    Given isStoredValueCustomer 為 false
    When 呼叫 StoredValueService.calculate 帶入任意費用
    Then 儲值扣款金額應為 0

  # ===================================================================
  # 後端 - 開啟/關閉儲值狀態
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 開啟儲值狀態後初始餘額為 0
    Given owners.json 中已有飼主 "owner_001"，isStoredValueCustomer 為 false
    When 呼叫 PUT "/api/owners/owner_001" 帶入 isStoredValueCustomer 為 true
    Then 回應 JSON 的 "isStoredValueCustomer" 應為 true
    And 回應 JSON 的 "storedValueBalance" 應為 0

  @backend @unit-test
  Scenario: 後端 - 設定儲值金額
    Given owners.json 中已有飼主 "owner_001"，isStoredValueCustomer 為 true，storedValueBalance 為 0
    When 呼叫 PUT "/api/owners/owner_001" 帶入 storedValueBalance 為 10000
    Then 回應 JSON 的 "storedValueBalance" 應為 10000

  @backend @unit-test
  Scenario: 後端 - 儲值金額不得為負數
    When 呼叫 PUT "/api/owners/owner_001" 帶入 storedValueBalance 為 -500
    Then 回應狀態碼應為 400
    And 回應 JSON 的 error.message 應包含 "儲值餘額不得小於 0"

  @backend @unit-test
  Scenario: 後端 - 關閉儲值狀態
    Given owners.json 中已有飼主 "owner_001"，isStoredValueCustomer 為 true，storedValueBalance 為 0
    When 呼叫 PUT "/api/owners/owner_001" 帶入 isStoredValueCustomer 為 false
    Then 回應 JSON 的 "isStoredValueCustomer" 應為 false

  # ===================================================================
  # 後端 - 美容紀錄保存時扣款
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 保存美容紀錄時自動扣除儲值金
    Given owners.json 中 "owner_001" storedValueBalance 為 5000
    And 相關預約與寵物資料已建立
    When 呼叫 POST "/api/grooming-records" 帶入總費用 500
    Then 回應 JSON 的 storedValueDeduction 應為 500
    And owners.json 中 "owner_001" storedValueBalance 應為 4500

  @backend @unit-test
  Scenario: 後端 - 儲值金歸零後美容師手動關閉儲值狀態
    Given owners.json 中 "owner_001" storedValueBalance 為 0
    When 呼叫 PUT "/api/owners/owner_001" 帶入 isStoredValueCustomer 為 false
    Then 回應狀態碼應為 200
    And 回應 JSON 的 "isStoredValueCustomer" 應為 false

  # ===================================================================
  # 後端 - 產生契約時帶入儲值金額
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 儲值型客戶產生契約帶入剩餘儲值金
    Given owners.json 中 "owner_001" storedValueBalance 為 5000
    And 美容紀錄費用合計為 500
    When 呼叫 POST "/api/contracts/generate" 帶入 recordId
    Then PDF 第 4 頁儲值金額應帶入 4500

  @backend @unit-test
  Scenario: 後端 - 儲值不足時產生契約帶入 0
    Given owners.json 中 "owner_001" storedValueBalance 為 300
    And 美容紀錄費用合計為 800
    When 呼叫 POST "/api/contracts/generate" 帶入 recordId
    Then PDF 第 4 頁儲值金額應帶入 0

  @backend @unit-test
  Scenario: 後端 - 非儲值型客戶產生契約時儲值欄位不帶入
    Given owners.json 中 "owner_002" isStoredValueCustomer 為 false
    When 為 "owner_002" 的寵物產生契約 PDF
    Then PDF 第 4 頁儲值金額欄位不應帶入

  # ===================================================================
  # 前端 - 儲值金額計算顯示
  # ===================================================================

  @frontend @unit-test
  Scenario: 前端 - 即時計算儲值扣款與現金支付
    Given 飼主 storedValueBalance 為 5000，isStoredValueCustomer 為 true
    When 使用者在美容費用欄位輸入 500
    Then 頁面應即時顯示：儲值扣款 500、現金支付 0、扣款後餘額 4500

  @frontend @unit-test
  Scenario: 前端 - 餘額不足時即時計算差額
    Given 飼主 storedValueBalance 為 300，isStoredValueCustomer 為 true
    When 使用者在美容費用欄位輸入 800
    Then 頁面應即時顯示：儲值扣款 300、現金支付 500、扣款後餘額 0

  @frontend @unit-test
  Scenario: 前端 - 非儲值型客戶不顯示儲值相關欄位
    Given 飼主 isStoredValueCustomer 為 false
    When 使用者在美容服務資料頁
    Then 儲值扣款區塊應隱藏或不顯示
    And 現金支付應直接等於總費用
