# language: zh-TW
# Generated by sa-expert
# Source: pm/features/veterinary_hospital.feature
# Project scan date: 2026-04-16

Feature: 獸醫院資訊
  對應模組：後端 OwnerService（獸醫院預設邏輯）+ PdfGenerator（套版邏輯）
  店家預設值：安欣動物醫院 / 03-3367775 / 桃園市桃園區中福街60號
  來源設定：settings.json 中的 defaultVeterinaryHospital

  Background:
    Given 系統已啟動且資料目錄已建立
    And settings.json 中店家預設獸醫院資訊如下：
      """
      {
        "defaultVeterinaryHospital": {
          "name": "安欣動物醫院",
          "phone": "03-3367775",
          "address": "桃園市桃園區中福街60號"
        }
      }
      """

  # ===================================================================
  # 後端 - 飼主指定獸醫院保存
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 飼主填寫指定獸醫院資訊並保存
    When 呼叫 POST "/api/owners" 帶入以下獸醫院資訊：
      """
      {
        "preferredAnimalHospital": "仁愛動物醫院",
        "preferredAnimalHospitalPhone": "03-1234567",
        "preferredAnimalHospitalAddress": "桃園市中壢區中正路100號"
      }
      """
    Then 回應狀態碼應為 201
    And 回應 JSON 的 "preferredAnimalHospital" 應為 "仁愛動物醫院"
    And 回應 JSON 的 "preferredAnimalHospitalPhone" 應為 "03-1234567"
    And 回應 JSON 的 "preferredAnimalHospitalAddress" 應為 "桃園市中壢區中正路100號"

  @backend @unit-test
  Scenario: 後端 - 飼主修改指定獸醫院資訊
    Given owners.json 中已有飼主 "owner_001"，preferredAnimalHospital 為 "仁愛動物醫院"
    When 呼叫 PUT "/api/owners/owner_001" 帶入 preferredAnimalHospital 為 "平安動物醫院"
    Then 回應 JSON 的 "preferredAnimalHospital" 應為 "平安動物醫院"

  @backend @unit-test
  Scenario: 後端 - 獸醫院資訊為選填不影響飼主保存
    When 呼叫 POST "/api/owners" 帶入所有必填欄位但不含獸醫院資訊
    Then 回應狀態碼應為 201
    And 回應 JSON 的 "preferredAnimalHospital" 應為空字串或 null

  @backend @unit-test
  Scenario: 後端 - 獸醫院部分欄位填寫
    When 呼叫 POST "/api/owners" 帶入 preferredAnimalHospital 為 "仁愛動物醫院" 但不含電話和地址
    Then 回應狀態碼應為 201
    And 回應 JSON 的 "preferredAnimalHospital" 應為 "仁愛動物醫院"
    And 回應 JSON 的 "preferredAnimalHospitalPhone" 應為空字串或 null

  # ===================================================================
  # 後端 - PDF 第 1 頁獸醫院帶入邏輯（Service 層）
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 飼主未填獸醫院時第 1 頁帶入店家預設
    Given 飼主 "owner_001" preferredAnimalHospital 為空
    When ContractService 準備第 1 頁套版資料
    Then 第 1 頁指定動物醫療機構應為 "安欣動物醫院"

  @backend @unit-test
  Scenario: 後端 - 飼主有填獸醫院時第 1 頁帶入飼主指定
    Given 飼主 "owner_001" preferredAnimalHospital 為 "仁愛動物醫院"
    When ContractService 準備第 1 頁套版資料
    Then 第 1 頁指定動物醫療機構應為 "仁愛動物醫院"

  # ===================================================================
  # 後端 - PDF 第 4 頁獸醫院帶入邏輯
  # ===================================================================

  @backend @unit-test
  Scenario: 後端 - 第 4 頁飼主有填獸醫院時帶入飼主指定資訊
    Given 飼主 "owner_001" 指定獸醫院：名稱 "仁愛動物醫院"、電話 "03-1234567"、地址 "桃園市中壢區中正路100號"
    When ContractService 準備第 4 頁套版資料
    Then 第 4 頁飼主指定獸醫院名稱應為 "仁愛動物醫院"
    And 第 4 頁飼主指定獸醫院電話應為 "03-1234567"
    And 第 4 頁飼主指定獸醫院地址應為 "桃園市中壢區中正路100號"

  @backend @unit-test
  Scenario: 後端 - 第 4 頁飼主未填獸醫院時留空
    Given 飼主 "owner_001" preferredAnimalHospital 為空
    When ContractService 準備第 4 頁套版資料
    Then 第 4 頁飼主指定獸醫院名稱應為空
    And 第 4 頁飼主指定獸醫院電話應為空
    And 第 4 頁飼主指定獸醫院地址應為空

  @backend @unit-test
  Scenario: 後端 - 第 4 頁店家預設獸醫院固定帶入
    When ContractService 準備第 4 頁套版資料
    Then 第 4 頁店家獸醫院名稱應為 "安欣動物醫院"
    And 第 4 頁店家獸醫院電話應為 "03-3367775"
    And 第 4 頁店家獸醫院地址應為 "桃園市桃園區中福街60號"

  @backend @unit-test
  Scenario: 後端 - 飼主有填獸醫院時第 4 頁同時帶入飼主指定與店家預設
    Given 飼主 "owner_001" preferredAnimalHospital 為 "仁愛動物醫院"
    When ContractService 準備第 4 頁套版資料
    Then 第 4 頁飼主指定獸醫院名稱應為 "仁愛動物醫院"
    And 第 4 頁店家獸醫院名稱應為 "安欣動物醫院"

  # ===================================================================
  # 前端 - 獸醫院欄位
  # ===================================================================

  @frontend @unit-test
  Scenario: 前端 - 飼主表單提供獸醫院選填欄位
    Given 使用者在飼主新增/編輯頁面
    Then 表單應提供指定動物醫療機構名稱、電話、地址三個選填欄位
    And 三個欄位均不標記為必填

  @frontend @unit-test
  Scenario: 前端 - 客戶填寫頁提供獸醫院欄位
    Given 使用者在客戶資料填寫頁
    Then 飼主資料區塊應包含指定動物醫療機構名稱、電話、地址三個欄位
    And 三個欄位均為選填
