// Auto-generated by sa-expert
// Feature: 預約管理
// Source: sa/features/appointment_management.feature
// 請填入實際的測試邏輯

const { Given, When, Then } = require('@cucumber/cucumber');
const assert = require('assert');

let response;

// ===== 新增預約 =====

When('呼叫 POST {string} 帶入 petId {string}、date {string}、time {string}', async function (endpoint, petId, date, time) {
  // TODO: response = await request(app).post(endpoint).send({ ownerId: 'owner_001', petId, date, time });
});

Then('回應 JSON 的 {string} 應為 {string}', function (field, expected) {
  // TODO: assert.strictEqual(response.body[field], expected);
});

Then('appointments.json 中應存在該筆預約', async function () {
  // TODO: 讀取 appointments.json 驗證
});

Then('appointments.json 中 {string} 應有兩筆預約', async function (petId) {
  // TODO: 讀取 appointments.json 計算該 petId 的預約數量
});

Then('appointments.json 中 {string} 應有兩筆預約', async function (date) {
  // TODO: 讀取 appointments.json 計算該日期的預約數量
});

// ===== 編輯預約 =====

Given('appointments.json 中已有預約 {string}，date {string}、time {string}', async function (id, date, time) {
  // TODO: 在測試用 appointments.json 中寫入預約資料
});

When('呼叫 PUT {string} 帶入 date {string}、time {string}', async function (endpoint, date, time) {
  // TODO: response = await request(app).put(endpoint).send({ date, time });
});

// ===== 取消預約 =====

Given('appointments.json 中已有預約 {string}，status 為 {string}', async function (id, status) {
  // TODO: 設定測試用預約狀態
});

When('呼叫 PUT {string} 帶入 status {string} 但無 cancelReason', async function (endpoint, status) {
  // TODO: response = await request(app).put(endpoint).send({ status });
});

Then('appointments.json 中 {string} 的資料不應被刪除', async function (id) {
  // TODO: 讀取 appointments.json 驗證資料仍存在
});

// ===== 前端情境 =====

Given('使用者在預約新增頁面', function () {
  // TODO: mount AppointmentForm component with Vue Test Utils
});

Given('使用者在預約詳細頁面，預約狀態為「已預約」', function () {
  // TODO: mount AppointmentDetail component with mock data
});

When('使用者未選擇飼主、寵物、日期或時間', function () {
  // TODO: 不填寫表單直接 submit
});

When('使用者選擇取消預約但未填寫取消原因', function () {
  // TODO: 觸發取消流程但不填寫原因
});

Then('表單應顯示對應的必填驗證錯誤', function () {
  // TODO: assert validation messages
});

Then('應顯示取消原因為必填的驗證錯誤', function () {
  // TODO: assert cancel reason validation error
});
