// Auto-generated by sa-expert
// Feature: 客戶資料填寫頁
// Source: sa/features/customer_form.feature
// 請填入實際的測試邏輯

const { Given, When, Then } = require('@cucumber/cucumber');
const assert = require('assert');

// ===== 前端 - 開啟客戶填寫頁 =====

Given('使用者（美容師）在系統管理畫面', function () {
  // TODO: mount main navigation component
});

When('使用者點擊「開啟客戶資料填寫」按鈕', function () {
  // TODO: trigger click on customer form button
});

Then('頁面應導向客戶資料填寫頁面路由（如 {string}）', function (route) {
  // TODO: assert router.currentRoute.path === route
});

Then('頁面不應顯示登入表單或帳號輸入欄位', function () {
  // TODO: assert no login form elements
});

// ===== 前端 - 表單欄位 =====

Given('使用者在客戶資料填寫頁', function () {
  // TODO: mount CustomerForm component
});

Then('表單應提供以下飼主欄位：', function (dataTable) {
  // TODO: 驗證所有欄位元素存在且必填屬性正確
});

Then('寵物表單應提供以下欄位：', function (dataTable) {
  // TODO: 驗證所有寵物欄位元素
});

// ===== 前端 - 多隻寵物 =====

When('客戶填寫第一隻寵物「{word}」的資料', function (petName) {
  // TODO: 填入第一隻寵物資料
});

When('客戶點擊「新增寵物」按鈕', function () {
  // TODO: trigger add pet button
});

Then('頁面應新增一組空白寵物表單', function () {
  // TODO: assert additional pet form section appeared
});

// ===== 前端 - 送出資料 =====

Given('客戶已完整填寫飼主資料與至少一隻寵物資料', function () {
  // TODO: fill all required fields
});

When('客戶按下「送出資料」按鈕', function () {
  // TODO: trigger submit button
});

Then('前端應先呼叫 POST {string} 建立飼主', function (endpoint) {
  // TODO: assert first API call is POST /api/owners
});

Then('API 回傳 {int} 後取得新飼主的 id', function (status) {
  // TODO: assert ownerId was captured from response
});

Then('前端應再呼叫 POST {string} 建立寵物，帶入 ownerId', function (endpoint) {
  // TODO: assert POST /api/pets called with correct ownerId
});

Then('所有 API 成功後應顯示「資料送出完成」的提示', function () {
  // TODO: assert success message
});

Then('頁面不應顯示其他客戶資料', function () {
  // TODO: assert no other customer data visible
});

// ===== 前端 - 必填欄位驗證 =====

When('客戶未填寫 {string} 但其他必填欄位皆有值', function (field) {
  // TODO: fill all fields except specified one
});

When('客戶按下送出資料按鈕', function () {
  // TODO: trigger submit
});

Then('表單應顯示 {string} 為必填的驗證錯誤', function (field) {
  // TODO: assert validation error for field
});

Then('不應呼叫任何 API', function () {
  // TODO: assert no API calls were made
});

Then('應顯示「至少需填寫一隻寵物」的驗證錯誤', function () {
  // TODO: assert pet validation error
});

// ===== 前端 - 畫面限制 =====

Then('頁面不應顯示任何既有飼主列表', function () {
  // TODO: assert no owner list element
});

Then('頁面不應提供刪除資料的按鈕', function () {
  // TODO: assert no delete button
});

Then('頁面不應提供瀏覽全部客戶的連結', function () {
  // TODO: assert no browse all link
});

Then('頁面不應提供預約管理功能', function () {
  // TODO: assert no appointment elements
});

Then('頁面不應提供行事曆功能', function () {
  // TODO: assert no calendar elements
});

Then('頁面不應提供 PDF 產生功能', function () {
  // TODO: assert no PDF generation elements
});

Then('頁面應顯示「返回店家操作」的連結或按鈕', function () {
  // TODO: assert back button exists
});

Then('頁面應導向店家管理首頁', function () {
  // TODO: assert navigation to home
});
