// Auto-generated by sa-expert
// Feature: 當日預約列表
// Source: sa/features/daily_appointment_list.feature
// 請填入實際的測試邏輯

const { Given, When, Then } = require('@cucumber/cucumber');
const assert = require('assert');

let response;

// ===== 後端 =====

Then('每筆預約應包含以下欄位：', function (dataTable) {
  // TODO: 驗證回應中每筆資料都包含指定欄位
  // const fields = dataTable.rows().map(row => row[0]);
  // response.body.forEach(item => fields.forEach(f => assert(f in item)));
});

// ===== 前端 =====

Given('使用者導向 {string}', function (path) {
  // TODO: mount DailyAppointmentList component with route param
  // TODO: mock GET /api/appointments/date/:date API
});

When('前端呼叫 GET {string} 並取得資料', function (endpoint) {
  // TODO: verify mock API call and populate component data
});

Then('列表應顯示以下欄位：{string}', function (fields) {
  // TODO: 驗證列表表頭包含所有欄位
});

Then('列表第一筆應為 {string} 的「{word}」', function (time, petName) {
  // TODO: assert first row content
});

Then('列表第二筆應為 {string} 的「{word}」', function (time, petName) {
  // TODO: assert second row content
});

Then('頁面應顯示日期標題 {string}', function (date) {
  // TODO: assert date title element text
});

When('使用者點擊「{word}」的預約列', function (petName) {
  // TODO: trigger click on appointment row
});

Then('頁面應導向 {word} 的美容服務資料輸入頁（帶入 appointmentId）', function (petName) {
  // TODO: assert router navigation with appointmentId param
});

Then('「{word}」的預約狀態應顯示為「已取消」樣式', function (petName) {
  // TODO: assert cancelled status styling (CSS class)
});

Then('應顯示取消原因「{string}」', function (reason) {
  // TODO: assert cancel reason text visible
});

Then('「{word}」的預約應顯示已產生契約的圖示或標示', function (petName) {
  // TODO: assert contract icon/badge visible
});

Then('應提供下載契約 PDF 的連結', function () {
  // TODO: assert download link element exists
});

Then('列表應顯示「當日無預約」的提示訊息', function () {
  // TODO: assert empty state message
});
