// Auto-generated by sa-expert
// Feature: 美容紀錄
// Source: sa/features/grooming_record.feature
// 請填入實際的測試邏輯

const { Given, When, Then } = require('@cucumber/cucumber');
const assert = require('assert');

let response;

// ===== 後端 - 建立美容紀錄 =====

When('呼叫 POST {string} 帶入總費用 {int}', async function (endpoint, totalCost) {
  // TODO: 組裝含費用的 services 陣列
  // TODO: response = await request(app).post(endpoint).send(requestBody);
});

When('呼叫 POST {string} 帶入 services 包含無效項目 {string}', async function (endpoint, item) {
  // TODO: response = await request(app).post(endpoint).send({ services: [{ item, price: 100 }] });
});

Then('回應 JSON 的 services 應包含洗澡 {int} 和美容 {int}', function (bathPrice, groomPrice) {
  // TODO: 驗證 services 陣列內容
});

Then('grooming-records.json 中應存在該筆紀錄', async function () {
  // TODO: 讀取 grooming-records.json 驗證
});

Then('owners.json 中 {string} 的 storedValueBalance 應更新為 {int}', async function (ownerId, balance) {
  // TODO: 讀取 owners.json 驗證儲值餘額
});

// ===== 後端 - 儲值金額扣款 =====

Given('owners.json 中 {string} storedValueBalance 為 {int}', async function (ownerId, balance) {
  // TODO: 設定測試用飼主儲值餘額
});

Then('回應 JSON 的 {string} 應為 {int}', function (field, value) {
  // TODO: assert.strictEqual(response.body[field], value);
});

Then('owners.json 中 {string} storedValueBalance 應為 {int}', async function (ownerId, balance) {
  // TODO: 讀取 owners.json 驗證
});

// ===== 後端 - 更新美容紀錄 =====

Given('grooming-records.json 中已有紀錄 {string}', async function (recordId) {
  // TODO: 在測試用 grooming-records.json 中寫入紀錄
});

When('呼叫 PUT {string} 修改 services[0].price 為 {int}', async function (endpoint, price) {
  // TODO: response = await request(app).put(endpoint).send(updatedData);
});

// ===== 前端 - 自動帶出資料 =====

Given('使用者導向美容服務資料頁，帶入 appointmentId {string}', function (appointmentId) {
  // TODO: mount GroomingRecordForm component with route param
  // TODO: mock 三支 API (appointment, owner, pet)
});

When('頁面載入時呼叫以下 API：', function (dataTable) {
  // TODO: 驗證所有列出的 API 都被呼叫
});

Then('頁面應自動顯示飼主姓名、電話、地址、身分證字號、緊急聯絡人', function () {
  // TODO: assert owner info elements are populated
});

Then('頁面應自動顯示寵物名稱、種類、品種、性別、年齡、結育狀態', function () {
  // TODO: assert pet info elements are populated
});

Then('頁面應自動帶入寵物個性勾選、身體狀態檢視、病史勾選', function () {
  // TODO: assert checkboxes and radio buttons are pre-selected
});

// ===== 前端 - 費用與儲值計算 =====

When('使用者勾選「洗澡」並輸入費用 {int}', function (price) {
  // TODO: check bath checkbox and input price
});

Then('頁面應自動顯示儲值金額扣款 {int}', function (deduction) {
  // TODO: assert deduction display
});

Then('頁面應自動顯示現金支付金額 {int}', function (cash) {
  // TODO: assert cash payment display
});

Then('頁面應自動顯示扣款後儲值餘額 {int}', function (remaining) {
  // TODO: assert remaining balance display
});

Then('儲值金額扣款區塊應隱藏或顯示為空', function () {
  // TODO: assert stored value section is hidden
});

// ===== 前端 - 保存與產生契約 =====

When('使用者按下保存按鈕', function () {
  // TODO: trigger save button click
});

Then('前端應呼叫 POST {string} 帶入完整資料', function (endpoint) {
  // TODO: assert mock API called with correct data
});

When('使用者按下產生契約按鈕', function () {
  // TODO: trigger generate contract button click
});

Then('應顯示「請至少選擇一個美容項目」的驗證錯誤', function () {
  // TODO: assert validation error message
});
