// Auto-generated by sa-expert
// Feature: 飼主管理
// Source: sa/features/owner_management.feature
// 請填入實際的測試邏輯

const { Given, When, Then } = require('@cucumber/cucumber');
const assert = require('assert');
const request = require('supertest'); // 或使用專案選定的 HTTP 測試工具

// TODO: 引入實際的 app instance
// const app = require('../../backend/src/app');

let response;
let requestBody;

// ===== Background =====

Given('系統已啟動且資料目錄已建立', async function () {
  // TODO: 確認測試用資料目錄存在
  // TODO: 初始化測試用 JSON 檔案（空資料）
});

Given('JSON 檔案 {string} 存在且格式正確', async function (filePath) {
  // TODO: 確認測試用 JSON 檔案存在且可讀取
});

// ===== 新增飼主 =====

Given('owners.json 中無任何飼主資料', async function () {
  // TODO: 將測試用 owners.json 設為空陣列 { "owners": [] }
});

When('呼叫 POST {string} 並帶入以下 JSON：', async function (endpoint, docString) {
  requestBody = JSON.parse(docString);
  // TODO: response = await request(app).post(endpoint).send(requestBody);
});

When('呼叫 POST {string} 並帶入缺少 {string} 的 JSON', async function (endpoint, fieldName) {
  // TODO: 組裝缺少指定欄位的 request body
  // TODO: response = await request(app).post(endpoint).send(requestBody);
});

Then('回應狀態碼應為 {int}', function (statusCode) {
  // TODO: assert.strictEqual(response.status, statusCode);
});

Then('回應 JSON 應包含自動產生的 {string} 欄位（格式如 {string}）', function (field, format) {
  // TODO: assert(response.body[field]);
  // TODO: assert(response.body[field].startsWith('owner_'));
});

Then('回應 JSON 的 {string} 應為 ISO 8601 格式', function (field) {
  // TODO: 驗證 ISO 8601 格式
});

Then('回應 JSON 的 {string} 應為 {string}', function (field, expectedValue) {
  // TODO: assert.strictEqual(response.body[field], expectedValue);
});

Then('回應 JSON 的 error.message 應包含 {string} 為必填', function (fieldName) {
  // TODO: assert(response.body.error.message.includes(fieldName));
});

Then('owners.json 中應存在一筆 name 為 {string} 的飼主資料', async function (name) {
  // TODO: 讀取 owners.json 驗證資料已寫入
});

Then('owners.json 不應新增任何資料', async function () {
  // TODO: 讀取 owners.json 驗證資料未被寫入
});

Then('回應 JSON 的 {string} 應為空字串或 null', function (field) {
  // TODO: assert(response.body[field] === '' || response.body[field] === null);
});

// ===== 編輯飼主 =====

Given('owners.json 中已有 id 為 {string} 的飼主「{word}」', async function (id, name) {
  // TODO: 在測試用 owners.json 中寫入指定飼主資料
});

When('呼叫 PUT {string} 並帶入以下 JSON：', async function (endpoint, docString) {
  requestBody = JSON.parse(docString);
  // TODO: response = await request(app).put(endpoint).send(requestBody);
});

When('呼叫 PUT {string} 並帶入 name 為空字串的 JSON', async function (endpoint) {
  // TODO: response = await request(app).put(endpoint).send({ name: '' });
});

When('呼叫 PUT {string} 並帶入合法 JSON', async function (endpoint) {
  // TODO: response = await request(app).put(endpoint).send(validOwnerData);
});

Then('回應 JSON 的 {string} 應晚於 {string}', function (field1, field2) {
  // TODO: 比較兩個時間欄位
});

Then('owners.json 中 {string} 的 phone 應為 {string}', async function (id, phone) {
  // TODO: 讀取 owners.json 驗證欄位值
});

// ===== 查詢飼主 =====

Given('owners.json 中已有飼主「{word}」和「{word}」', async function (name1, name2) {
  // TODO: 在測試用 owners.json 中寫入兩筆飼主
});

When('呼叫 GET {string}', async function (endpoint) {
  // TODO: response = await request(app).get(endpoint);
});

Then('回應 JSON 陣列應包含 name 為 {string} 的飼主', function (name) {
  // TODO: assert(response.body.some(o => o.name === name));
});

Then('回應 JSON 陣列不應包含 name 為 {string} 的飼主', function (name) {
  // TODO: assert(!response.body.some(o => o.name === name));
});

Then('回應 JSON 陣列應為空陣列', function () {
  // TODO: assert.strictEqual(response.body.length, 0);
});

// ===== 儲值金額管理 =====

Given('owners.json 中已有飼主 {string}，isStoredValueCustomer 為 {word}', async function (id, status) {
  // TODO: 在測試用 owners.json 中設定飼主儲值狀態
});

When('呼叫 PUT {string} 帶入 isStoredValueCustomer 為 {word}', async function (endpoint, value) {
  // TODO: response = await request(app).put(endpoint).send({ isStoredValueCustomer: value === 'true' });
});

When('呼叫 PUT {string} 帶入 storedValueBalance 為 {int}', async function (endpoint, balance) {
  // TODO: response = await request(app).put(endpoint).send({ storedValueBalance: balance });
});

Then('回應 JSON 的 {string} 應為 {word}', function (field, expected) {
  // TODO: 根據型別比較（boolean / number / string）
});

Then('owners.json 中 {string} 的 storedValueBalance 應為 {int}', async function (id, balance) {
  // TODO: 讀取 owners.json 驗證
});

Then('owners.json 中 {string} 的 storedValueBalance 不應被更新', async function (id) {
  // TODO: 讀取 owners.json 驗證值未改變
});

// ===== 前端情境 =====

Given('使用者在飼主新增頁面', function () {
  // TODO: mount Vue component (OwnerForm) with Vue Test Utils
});

Given('使用者在飼主編輯頁面', function () {
  // TODO: mount Vue component with mock API data
});

Given('使用者在飼主列表頁面', function () {
  // TODO: mount Vue component (OwnerList)
});

When('使用者未填寫任何欄位直接按下保存按鈕', async function () {
  // TODO: trigger submit on empty form
});

Then('表單應顯示所有必填欄位的驗證錯誤訊息', function () {
  // TODO: assert validation error messages are displayed
});

Then('不應呼叫 POST {string} API', function (endpoint) {
  // TODO: assert mock API was not called
});
