// Auto-generated by sa-expert
// Feature: 寵物管理
// Source: sa/features/pet_management.feature
// 請填入實際的測試邏輯

const { Given, When, Then } = require('@cucumber/cucumber');
const assert = require('assert');

let response;

// ===== Background =====

Given('JSON 檔案 {string} 中已有飼主 {string}（{word}）', async function (file, ownerId, name) {
  // TODO: 在測試用 owners.json 中寫入飼主資料
});

// ===== 新增寵物 =====

When('呼叫 POST {string} 並帶入以下 JSON：', async function (endpoint, docString) {
  // TODO: response = await request(app).post(endpoint).send(JSON.parse(docString));
});

When('呼叫 POST {string} 並帶入缺少 {string} 的 JSON（其他必填欄位皆有值）', async function (endpoint, field) {
  // TODO: 組裝缺少指定欄位的 request body 並呼叫 API
});

When('呼叫 POST {string} 帶入 personality 為空陣列', async function (endpoint) {
  // TODO: response = await request(app).post(endpoint).send({ ...validPetData, personality: [] });
});

When('呼叫 POST {string} 帶入 personality 為 {string}', async function (endpoint, personalities) {
  // TODO: 解析 personality 陣列並呼叫 API
});

When('呼叫 POST {string} 帶入 physicalExamination 如下：', async function (endpoint, docString) {
  // TODO: 帶入指定的身體狀態並呼叫 API
});

When('呼叫 POST {string} 帶入 medicalHistory 為 {string} 且 medicalHistoryOther 為 {string}', async function (endpoint, history, other) {
  // TODO: 帶入病史資料並呼叫 API
});

When('呼叫 POST {string} 帶入 chipNumber 為 {string}', async function (endpoint, chip) {
  // TODO: 帶入晶片號碼並呼叫 API
});

Then('回應 JSON 的 {string} 應包含 {string}', function (field, value) {
  // TODO: assert(response.body[field].includes(value));
});

Then('回應 JSON 的 {string} 不應包含 {string}', function (field, value) {
  // TODO: assert(!response.body[field].includes(value));
});

// ===== 取得飼主的寵物 =====

Given('pets.json 中已有寵物 {string}（{word}）關聯 {string}', async function (petId, petName, ownerId) {
  // TODO: 在測試用 pets.json 中寫入寵物資料
});

// ===== 編輯寵物 =====

Given('pets.json 中已有寵物 {string}（{word}），age 為 {string}', async function (petId, name, age) {
  // TODO: 設定測試用寵物資料
});

When('呼叫 PUT {string} 帶入 age 為 {string}', async function (endpoint, age) {
  // TODO: response = await request(app).put(endpoint).send({ age });
});

When('呼叫 PUT {string} 帶入 personality 為 {string}', async function (endpoint, personalities) {
  // TODO: 帶入新的 personality 並呼叫 API
});

When('呼叫 PUT {string} 帶入 isNeutered 為 {word}', async function (endpoint, value) {
  // TODO: response = await request(app).put(endpoint).send({ isNeutered: value === 'true' });
});

// ===== 前端情境 =====

Given('使用者在寵物新增頁面', function () {
  // TODO: mount PetForm component with Vue Test Utils
});

Given('使用者在寵物表單頁面', function () {
  // TODO: mount PetForm component
});

Then('寵物個性區塊應顯示以下選項：{string}', function (options) {
  // TODO: 驗證所有選項都已渲染
});

Then('身體狀態區塊應顯示：{string}', function (description) {
  // TODO: 驗證身體狀態檢視元件
});

Then('病史區塊應顯示以下選項：{string}', function (options) {
  // TODO: 驗證所有病史選項都已渲染
});

Then('選擇「其它」時應出現自由輸入欄位', function () {
  // TODO: 勾選「其它」後驗證自由輸入欄位出現
});
