// Auto-generated by sa-expert
// Feature: 儲值金額完整流程
// Source: sa/features/stored_value.feature
// 請填入實際的測試邏輯

const { Given, When, Then } = require('@cucumber/cucumber');
const assert = require('assert');

// TODO: 引入 StoredValueService
// const { StoredValueService } = require('../../backend/src/services/storedValueService');

let calcResult;

// ===== Service 層儲值扣款計算 =====

Given('儲值餘額為 {int}', function (balance) {
  this.balance = balance;
});

Given('本次費用合計為 {int}', function (totalCost) {
  this.totalCost = totalCost;
});

When('呼叫 StoredValueService.calculate\\(balance, totalCost)', function () {
  // TODO: calcResult = StoredValueService.calculate(this.balance, this.totalCost);
});

When('呼叫 StoredValueService.calculate\\({int}, {int})', function (balance, totalCost) {
  // TODO: calcResult = StoredValueService.calculate(balance, totalCost);
});

When('呼叫 StoredValueService.calculate 帶入任意費用', function () {
  // TODO: calcResult = StoredValueService.calculate(0, 500);
  // 注意：非儲值型客戶在呼叫前已由 Service 層判斷，此處測試 calculate 函式本身
});

Then('儲值扣款金額應為 {int}', function (deduction) {
  // TODO: assert.strictEqual(calcResult.storedValueDeduction, deduction);
});

Then('現金支付金額應為 {int}', function (cash) {
  // TODO: assert.strictEqual(calcResult.cashPayment, cash);
});

Then('扣款後餘額應為 {int}', function (remaining) {
  // TODO: assert.strictEqual(calcResult.remainingBalance, remaining);
});

Then('扣款後餘額不應小於 0', function () {
  // TODO: assert(calcResult.remainingBalance >= 0);
});

Given('isStoredValueCustomer 為 false', function () {
  this.isStoredValueCustomer = false;
});

// ===== 前端 - 即時計算 =====

Given('飼主 storedValueBalance 為 {int}，isStoredValueCustomer 為 {word}', function (balance, status) {
  // TODO: set mock owner data for component
});

When('使用者在美容費用欄位輸入 {int}', function (amount) {
  // TODO: input amount in fee field
});

Then('頁面應即時顯示：儲值扣款 {int}、現金支付 {int}、扣款後餘額 {int}', function (deduction, cash, remaining) {
  // TODO: assert calculated fields display
});

Given('飼主 isStoredValueCustomer 為 false', function () {
  // TODO: set mock owner data
});

Then('儲值扣款區塊應隱藏或不顯示', function () {
  // TODO: assert stored value section not visible
});

Then('現金支付應直接等於總費用', function () {
  // TODO: assert cash equals total
});
