// Auto-generated by sa-expert
// Feature: 獸醫院資訊
// Source: sa/features/veterinary_hospital.feature
// 請填入實際的測試邏輯

const { Given, When, Then } = require('@cucumber/cucumber');
const assert = require('assert');

let response;

// ===== 後端 - 獸醫院保存 =====

When('呼叫 POST {string} 帶入以下獸醫院資訊：', async function (endpoint, docString) {
  const hospitalInfo = JSON.parse(docString);
  // TODO: 組合完整 owner 資料（含必填欄位 + 獸醫院資訊）
  // TODO: response = await request(app).post(endpoint).send(fullOwnerData);
});

When('呼叫 PUT {string} 帶入 preferredAnimalHospital 為 {string}', async function (endpoint, hospital) {
  // TODO: response = await request(app).put(endpoint).send({ preferredAnimalHospital: hospital });
});

When('呼叫 POST {string} 帶入 preferredAnimalHospital 為 {string} 但不含電話和地址', async function (endpoint, hospital) {
  // TODO: 組合含獸醫院名稱但不含電話地址的資料
});

// ===== 後端 - PDF 套版邏輯（Service 層） =====

Given('飼主 {string} preferredAnimalHospital 為空', function (ownerId) {
  // TODO: 設定飼主獸醫院為空
});

Given('飼主 {string} preferredAnimalHospital 為 {string}', function (ownerId, hospital) {
  // TODO: 設定飼主指定獸醫院
});

Given('飼主 {string} 指定獸醫院：名稱 {string}、電話 {string}、地址 {string}', function (ownerId, name, phone, address) {
  // TODO: 設定飼主完整獸醫院資訊
});

When('ContractService 準備第 {int} 頁套版資料', function (page) {
  // TODO: 呼叫 ContractService 的套版資料準備方法
  // TODO: this.templateData = contractService.preparePageData(page, ownerData, petData, recordData);
});

Then('第 {int} 頁指定動物醫療機構應為 {string}', function (page, expected) {
  // TODO: assert.strictEqual(this.templateData.veterinaryHospital, expected);
});

Then('第 {int} 頁飼主指定獸醫院名稱應為 {string}', function (page, expected) {
  // TODO: assert.strictEqual(this.templateData.ownerVetName, expected);
});

Then('第 {int} 頁飼主指定獸醫院名稱應為空', function (page) {
  // TODO: assert(!this.templateData.ownerVetName || this.templateData.ownerVetName === '');
});

Then('第 {int} 頁飼主指定獸醫院電話應為 {string}', function (page, expected) {
  // TODO: assert.strictEqual(this.templateData.ownerVetPhone, expected);
});

Then('第 {int} 頁飼主指定獸醫院電話應為空', function (page) {
  // TODO: assert(!this.templateData.ownerVetPhone);
});

Then('第 {int} 頁飼主指定獸醫院地址應為 {string}', function (page, expected) {
  // TODO: assert.strictEqual(this.templateData.ownerVetAddress, expected);
});

Then('第 {int} 頁飼主指定獸醫院地址應為空', function (page) {
  // TODO: assert(!this.templateData.ownerVetAddress);
});

Then('第 {int} 頁店家獸醫院名稱應為 {string}', function (page, expected) {
  // TODO: assert.strictEqual(this.templateData.defaultVetName, expected);
});

Then('第 {int} 頁店家獸醫院電話應為 {string}', function (page, expected) {
  // TODO: assert.strictEqual(this.templateData.defaultVetPhone, expected);
});

Then('第 {int} 頁店家獸醫院地址應為 {string}', function (page, expected) {
  // TODO: assert.strictEqual(this.templateData.defaultVetAddress, expected);
});

// ===== 前端 =====

Given('使用者在飼主新增/編輯頁面', function () {
  // TODO: mount OwnerForm component
});

Then('表單應提供指定動物醫療機構名稱、電話、地址三個選填欄位', function () {
  // TODO: assert three vet hospital input fields exist
});

Then('三個欄位均不標記為必填', function () {
  // TODO: assert no required attribute on vet hospital fields
});

Then('飼主資料區塊應包含指定動物醫療機構名稱、電話、地址三個欄位', function () {
  // TODO: assert vet hospital fields in customer form
});

Then('三個欄位均為選填', function () {
  // TODO: assert no required validation on these fields
});
